# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt\ui\diffs.ui'
#
# Created: Tue Jul 16 17:26:47 2013
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Diffs(object):
    def setupUi(self, Diffs):
        Diffs.setObjectName(_fromUtf8("Diffs"))
        Diffs.resize(1078, 389)
        Diffs.setWindowTitle(QtGui.QApplication.translate("Diffs", "Diffs", None, QtGui.QApplication.UnicodeUTF8))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/monokuma-green.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Diffs.setWindowIcon(icon)
        Diffs.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayout_3 = QtGui.QVBoxLayout(Diffs)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.chkNotBoth = QtGui.QCheckBox(Diffs)
        self.chkNotBoth.setText(QtGui.QApplication.translate("Diffs", "Show Files Not in Both Dirs", None, QtGui.QApplication.UnicodeUTF8))
        self.chkNotBoth.setObjectName(_fromUtf8("chkNotBoth"))
        self.gridLayout.addWidget(self.chkNotBoth, 1, 1, 1, 1)
        self.chkShowSame = QtGui.QCheckBox(Diffs)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Meiryo UI"))
        self.chkShowSame.setFont(font)
        self.chkShowSame.setText(QtGui.QApplication.translate("Diffs", "Show Identical Files", None, QtGui.QApplication.UnicodeUTF8))
        self.chkShowSame.setObjectName(_fromUtf8("chkShowSame"))
        self.gridLayout.addWidget(self.chkShowSame, 1, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.treeResults = QtGui.QTreeWidget(Diffs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeResults.sizePolicy().hasHeightForWidth())
        self.treeResults.setSizePolicy(sizePolicy)
        self.treeResults.setMinimumSize(QtCore.QSize(0, 0))
        self.treeResults.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.treeResults.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.treeResults.setIndentation(15)
        self.treeResults.setObjectName(_fromUtf8("treeResults"))
        self.treeResults.headerItem().setText(0, QtGui.QApplication.translate("Diffs", "Results (0)", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout.addWidget(self.treeResults)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.lblDir1 = QtGui.QLabel(Diffs)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Meiryo UI"))
        font.setPointSize(10)
        self.lblDir1.setFont(font)
        self.lblDir1.setText(QtGui.QApplication.translate("Diffs", "DIR 1", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDir1.setObjectName(_fromUtf8("lblDir1"))
        self.verticalLayout_4.addWidget(self.lblDir1)
        self.label = QtGui.QLabel(Diffs)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Meiryo UI"))
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setText(QtGui.QApplication.translate("Diffs", "Translated", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_4.addWidget(self.label)
        self.txtTranslated1 = QtGui.QPlainTextEdit(Diffs)
        self.txtTranslated1.setMinimumSize(QtCore.QSize(375, 80))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Meiryo UI"))
        font.setPointSize(10)
        self.txtTranslated1.setFont(font)
        self.txtTranslated1.setTabChangesFocus(True)
        self.txtTranslated1.setReadOnly(True)
        self.txtTranslated1.setOverwriteMode(False)
        self.txtTranslated1.setTabStopWidth(20)
        self.txtTranslated1.setObjectName(_fromUtf8("txtTranslated1"))
        self.verticalLayout_4.addWidget(self.txtTranslated1)
        self.label_2 = QtGui.QLabel(Diffs)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Meiryo UI"))
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setText(QtGui.QApplication.translate("Diffs", "Original", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_4.addWidget(self.label_2)
        self.txtOriginal1 = QtGui.QPlainTextEdit(Diffs)
        self.txtOriginal1.setMinimumSize(QtCore.QSize(375, 80))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Meiryo UI"))
        font.setPointSize(10)
        self.txtOriginal1.setFont(font)
        self.txtOriginal1.setTabChangesFocus(True)
        self.txtOriginal1.setReadOnly(True)
        self.txtOriginal1.setOverwriteMode(False)
        self.txtOriginal1.setTabStopWidth(20)
        self.txtOriginal1.setObjectName(_fromUtf8("txtOriginal1"))
        self.verticalLayout_4.addWidget(self.txtOriginal1)
        self.label_3 = QtGui.QLabel(Diffs)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Meiryo UI"))
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setText(QtGui.QApplication.translate("Diffs", "Comments", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_4.addWidget(self.label_3)
        self.txtComments1 = QtGui.QPlainTextEdit(Diffs)
        self.txtComments1.setMinimumSize(QtCore.QSize(375, 80))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Meiryo UI"))
        font.setPointSize(10)
        self.txtComments1.setFont(font)
        self.txtComments1.setTabChangesFocus(True)
        self.txtComments1.setReadOnly(True)
        self.txtComments1.setOverwriteMode(False)
        self.txtComments1.setTabStopWidth(20)
        self.txtComments1.setObjectName(_fromUtf8("txtComments1"))
        self.verticalLayout_4.addWidget(self.txtComments1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lblDir2 = QtGui.QLabel(Diffs)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Meiryo UI"))
        font.setPointSize(10)
        self.lblDir2.setFont(font)
        self.lblDir2.setText(QtGui.QApplication.translate("Diffs", "DIR 2", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDir2.setObjectName(_fromUtf8("lblDir2"))
        self.verticalLayout_2.addWidget(self.lblDir2)
        self.label_14 = QtGui.QLabel(Diffs)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Meiryo UI"))
        font.setPointSize(9)
        self.label_14.setFont(font)
        self.label_14.setText(QtGui.QApplication.translate("Diffs", "Translated", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_2.addWidget(self.label_14)
        self.txtTranslated2 = QtGui.QPlainTextEdit(Diffs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtTranslated2.sizePolicy().hasHeightForWidth())
        self.txtTranslated2.setSizePolicy(sizePolicy)
        self.txtTranslated2.setMinimumSize(QtCore.QSize(375, 80))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Meiryo UI"))
        font.setPointSize(10)
        self.txtTranslated2.setFont(font)
        self.txtTranslated2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.txtTranslated2.setTabChangesFocus(True)
        self.txtTranslated2.setLineWrapMode(QtGui.QPlainTextEdit.WidgetWidth)
        self.txtTranslated2.setReadOnly(True)
        self.txtTranslated2.setPlainText(_fromUtf8(""))
        self.txtTranslated2.setTabStopWidth(20)
        self.txtTranslated2.setObjectName(_fromUtf8("txtTranslated2"))
        self.verticalLayout_2.addWidget(self.txtTranslated2)
        self.label_15 = QtGui.QLabel(Diffs)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Meiryo UI"))
        font.setPointSize(9)
        self.label_15.setFont(font)
        self.label_15.setText(QtGui.QApplication.translate("Diffs", "Original", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_2.addWidget(self.label_15)
        self.txtOriginal2 = QtGui.QPlainTextEdit(Diffs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtOriginal2.sizePolicy().hasHeightForWidth())
        self.txtOriginal2.setSizePolicy(sizePolicy)
        self.txtOriginal2.setMinimumSize(QtCore.QSize(375, 80))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Meiryo UI"))
        font.setPointSize(10)
        self.txtOriginal2.setFont(font)
        self.txtOriginal2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.txtOriginal2.setTabChangesFocus(True)
        self.txtOriginal2.setLineWrapMode(QtGui.QPlainTextEdit.WidgetWidth)
        self.txtOriginal2.setReadOnly(True)
        self.txtOriginal2.setPlainText(_fromUtf8(""))
        self.txtOriginal2.setTabStopWidth(20)
        self.txtOriginal2.setObjectName(_fromUtf8("txtOriginal2"))
        self.verticalLayout_2.addWidget(self.txtOriginal2)
        self.label_16 = QtGui.QLabel(Diffs)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Meiryo UI"))
        font.setPointSize(9)
        self.label_16.setFont(font)
        self.label_16.setText(QtGui.QApplication.translate("Diffs", "Comments", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_2.addWidget(self.label_16)
        self.txtComments2 = QtGui.QPlainTextEdit(Diffs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtComments2.sizePolicy().hasHeightForWidth())
        self.txtComments2.setSizePolicy(sizePolicy)
        self.txtComments2.setMinimumSize(QtCore.QSize(375, 80))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Meiryo UI"))
        font.setPointSize(10)
        self.txtComments2.setFont(font)
        self.txtComments2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.txtComments2.setTabChangesFocus(True)
        self.txtComments2.setLineWrapMode(QtGui.QPlainTextEdit.WidgetWidth)
        self.txtComments2.setReadOnly(True)
        self.txtComments2.setPlainText(_fromUtf8(""))
        self.txtComments2.setTabStopWidth(20)
        self.txtComments2.setObjectName(_fromUtf8("txtComments2"))
        self.verticalLayout_2.addWidget(self.txtComments2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.buttonBox = QtGui.QDialogButtonBox(Diffs)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(Diffs)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Diffs.reject)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Diffs.accept)
        QtCore.QObject.connect(self.treeResults, QtCore.SIGNAL(_fromUtf8("currentItemChanged(QTreeWidgetItem*,QTreeWidgetItem*)")), Diffs.changedSelection)
        QtCore.QObject.connect(self.chkShowSame, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), Diffs.show_files)
        QtCore.QObject.connect(self.chkNotBoth, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), Diffs.show_files)
        QtCore.QMetaObject.connectSlotsByName(Diffs)
        Diffs.setTabOrder(self.treeResults, self.txtTranslated2)
        Diffs.setTabOrder(self.txtTranslated2, self.txtOriginal2)
        Diffs.setTabOrder(self.txtOriginal2, self.txtComments2)
        Diffs.setTabOrder(self.txtComments2, self.buttonBox)

    def retranslateUi(self, Diffs):
        pass

import icons_rc
