# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt\ui\editor.ui'
#
# Created: Tue Jul 16 17:26:47 2013
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Editor(object):
    def setupUi(self, Editor):
        Editor.setObjectName(_fromUtf8("Editor"))
        Editor.resize(1430, 648)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Editor.sizePolicy().hasHeightForWidth())
        Editor.setSizePolicy(sizePolicy)
        Editor.setMinimumSize(QtCore.QSize(1430, 648))
        Editor.setMaximumSize(QtCore.QSize(1430, 648))
        Editor.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        Editor.setWindowTitle(QtGui.QApplication.translate("Editor", "The Super Duper Script Editor 2", None, QtGui.QApplication.UnicodeUTF8))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/monokuma.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Editor.setWindowIcon(icon)
        Editor.setAutoFillBackground(False)
        Editor.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        Editor.setIconSize(QtCore.QSize(16, 16))
        Editor.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        Editor.setDocumentMode(False)
        Editor.setTabShape(QtGui.QTabWidget.Rounded)
        Editor.setDockNestingEnabled(False)
        self.centralwidget = QtGui.QWidget(Editor)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.lblOriginal = QtGui.QLabel(self.centralwidget)
        self.lblOriginal.setGeometry(QtCore.QRect(10, 300, 480, 272))
        self.lblOriginal.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.lblOriginal.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblOriginal.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblOriginal.setText(_fromUtf8(""))
        self.lblOriginal.setObjectName(_fromUtf8("lblOriginal"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(500, 0, 131, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Meiryo UI"))
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setText(QtGui.QApplication.translate("Editor", "Translated", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(500, 290, 101, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Meiryo UI"))
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setText(QtGui.QApplication.translate("Editor", "Original", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(960, 10, 131, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Meiryo UI"))
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setText(QtGui.QApplication.translate("Editor", "Script Files", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.lblTranslated = QtGui.QLabel(self.centralwidget)
        self.lblTranslated.setGeometry(QtCore.QRect(10, 10, 480, 272))
        self.lblTranslated.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.lblTranslated.setAutoFillBackground(False)
        self.lblTranslated.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblTranslated.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblTranslated.setText(_fromUtf8(""))
        self.lblTranslated.setObjectName(_fromUtf8("lblTranslated"))
        self.txtTranslated = SmartTextEdit(self.centralwidget)
        self.txtTranslated.setGeometry(QtCore.QRect(500, 40, 451, 91))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtTranslated.sizePolicy().hasHeightForWidth())
        self.txtTranslated.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Meiryo UI"))
        font.setPointSize(11)
        self.txtTranslated.setFont(font)
        self.txtTranslated.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.txtTranslated.setTabStopWidth(20)
        self.txtTranslated.setObjectName(_fromUtf8("txtTranslated"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 280, 941, 24))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(500, 440, 121, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Meiryo UI"))
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setText(QtGui.QApplication.translate("Editor", "Comments", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.txtComments = ReferenceEdit(self.centralwidget)
        self.txtComments.setGeometry(QtCore.QRect(500, 470, 451, 102))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Meiryo UI"))
        font.setPointSize(10)
        self.txtComments.setFont(font)
        self.txtComments.setTabStopWidth(20)
        self.txtComments.setObjectName(_fromUtf8("txtComments"))
        self.groupScene = QtGui.QGroupBox(self.centralwidget)
        self.groupScene.setEnabled(True)
        self.groupScene.setGeometry(QtCore.QRect(500, 140, 451, 141))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupScene.setFont(font)
        self.groupScene.setTitle(QtGui.QApplication.translate("Editor", "Scene", None, QtGui.QApplication.UnicodeUTF8))
        self.groupScene.setFlat(False)
        self.groupScene.setCheckable(False)
        self.groupScene.setObjectName(_fromUtf8("groupScene"))
        self.label_2 = QtGui.QLabel(self.groupScene)
        self.label_2.setGeometry(QtCore.QRect(0, 50, 61, 22))
        self.label_2.setText(QtGui.QApplication.translate("Editor", "Sprite", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label = QtGui.QLabel(self.groupScene)
        self.label.setGeometry(QtCore.QRect(0, 20, 61, 22))
        self.label.setText(QtGui.QApplication.translate("Editor", "Speaker", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_8 = QtGui.QLabel(self.groupScene)
        self.label_8.setGeometry(QtCore.QRect(0, 80, 61, 22))
        self.label_8.setText(QtGui.QApplication.translate("Editor", "Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_5 = QtGui.QLabel(self.groupScene)
        self.label_5.setGeometry(QtCore.QRect(219, 50, 61, 22))
        self.label_5.setText(QtGui.QApplication.translate("Editor", "Playback", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_11 = QtGui.QLabel(self.groupScene)
        self.label_11.setGeometry(QtCore.QRect(220, 110, 61, 22))
        self.label_11.setText(QtGui.QApplication.translate("Editor", "Scene Info", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.groupScene)
        self.label_12.setGeometry(QtCore.QRect(0, 110, 61, 22))
        self.label_12.setText(QtGui.QApplication.translate("Editor", "Area", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.btnPlayVoice = QtGui.QPushButton(self.groupScene)
        self.btnPlayVoice.setEnabled(True)
        self.btnPlayVoice.setGeometry(QtCore.QRect(289, 50, 27, 21))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.btnPlayVoice.setFont(font)
        self.btnPlayVoice.setStyleSheet(_fromUtf8("padding-left: 1px;"))
        self.btnPlayVoice.setText(QtGui.QApplication.translate("Editor", "▶", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPlayVoice.setShortcut(QtGui.QApplication.translate("Editor", "F5", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPlayVoice.setCheckable(False)
        self.btnPlayVoice.setFlat(False)
        self.btnPlayVoice.setObjectName(_fromUtf8("btnPlayVoice"))
        self.lblScene = QtGui.QLabel(self.groupScene)
        self.lblScene.setGeometry(QtCore.QRect(290, 110, 151, 22))
        self.lblScene.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblScene.setFrameShadow(QtGui.QFrame.Plain)
        self.lblScene.setLineWidth(1)
        self.lblScene.setMidLineWidth(0)
        self.lblScene.setText(QtGui.QApplication.translate("Editor", "Chapter 9, Scene 666", None, QtGui.QApplication.UnicodeUTF8))
        self.lblScene.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.lblScene.setObjectName(_fromUtf8("lblScene"))
        self.lblSpeaker = QtGui.QLabel(self.groupScene)
        self.lblSpeaker.setGeometry(QtCore.QRect(70, 20, 151, 22))
        self.lblSpeaker.setAutoFillBackground(False)
        self.lblSpeaker.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblSpeaker.setFrameShadow(QtGui.QFrame.Plain)
        self.lblSpeaker.setLineWidth(1)
        self.lblSpeaker.setMidLineWidth(0)
        self.lblSpeaker.setText(QtGui.QApplication.translate("Editor", "Mikan Tsumiki", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSpeaker.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.lblSpeaker.setObjectName(_fromUtf8("lblSpeaker"))
        self.lblSprite = QtGui.QLabel(self.groupScene)
        self.lblSprite.setGeometry(QtCore.QRect(70, 50, 151, 22))
        self.lblSprite.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblSprite.setFrameShadow(QtGui.QFrame.Plain)
        self.lblSprite.setLineWidth(1)
        self.lblSprite.setMidLineWidth(0)
        self.lblSprite.setText(QtGui.QApplication.translate("Editor", "Mikan Tsumiki", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSprite.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.lblSprite.setObjectName(_fromUtf8("lblSprite"))
        self.lblMode = QtGui.QLabel(self.groupScene)
        self.lblMode.setGeometry(QtCore.QRect(70, 80, 151, 22))
        self.lblMode.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblMode.setFrameShadow(QtGui.QFrame.Plain)
        self.lblMode.setLineWidth(1)
        self.lblMode.setMidLineWidth(0)
        self.lblMode.setText(QtGui.QApplication.translate("Editor", "Normal", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMode.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.lblMode.setObjectName(_fromUtf8("lblMode"))
        self.lblArea = QtGui.QLabel(self.groupScene)
        self.lblArea.setGeometry(QtCore.QRect(70, 110, 151, 22))
        self.lblArea.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblArea.setFrameShadow(QtGui.QFrame.Plain)
        self.lblArea.setLineWidth(1)
        self.lblArea.setMidLineWidth(0)
        self.lblArea.setText(QtGui.QApplication.translate("Editor", "Titty Typhoon (Parking Lot)", None, QtGui.QApplication.UnicodeUTF8))
        self.lblArea.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.lblArea.setObjectName(_fromUtf8("lblArea"))
        self.label_17 = QtGui.QLabel(self.groupScene)
        self.label_17.setGeometry(QtCore.QRect(220, 20, 61, 22))
        self.label_17.setText(QtGui.QApplication.translate("Editor", "Voice", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.lblVoice = QtGui.QLabel(self.groupScene)
        self.lblVoice.setGeometry(QtCore.QRect(290, 20, 151, 22))
        self.lblVoice.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblVoice.setFrameShadow(QtGui.QFrame.Plain)
        self.lblVoice.setLineWidth(1)
        self.lblVoice.setMidLineWidth(0)
        self.lblVoice.setText(QtGui.QApplication.translate("Editor", "Mikan Tsumiki", None, QtGui.QApplication.UnicodeUTF8))
        self.lblVoice.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.lblVoice.setObjectName(_fromUtf8("lblVoice"))
        self.label_18 = QtGui.QLabel(self.groupScene)
        self.label_18.setGeometry(QtCore.QRect(220, 80, 61, 22))
        self.label_18.setText(QtGui.QApplication.translate("Editor", "Special", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.lblSpecial = QtGui.QLabel(self.groupScene)
        self.lblSpecial.setGeometry(QtCore.QRect(290, 80, 151, 22))
        self.lblSpecial.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblSpecial.setFrameShadow(QtGui.QFrame.Plain)
        self.lblSpecial.setLineWidth(1)
        self.lblSpecial.setMidLineWidth(0)
        self.lblSpecial.setText(QtGui.QApplication.translate("Editor", "N/A", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSpecial.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.lblSpecial.setObjectName(_fromUtf8("lblSpecial"))
        self.btnStopVoice = QtGui.QPushButton(self.groupScene)
        self.btnStopVoice.setGeometry(QtCore.QRect(315, 50, 27, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(9)
        font.setKerning(True)
        self.btnStopVoice.setFont(font)
        self.btnStopVoice.setStyleSheet(_fromUtf8("padding-left: 1px;\n"
"padding-top: 0px;"))
        self.btnStopVoice.setText(QtGui.QApplication.translate("Editor", "■", None, QtGui.QApplication.UnicodeUTF8))
        self.btnStopVoice.setShortcut(QtGui.QApplication.translate("Editor", "F6", None, QtGui.QApplication.UnicodeUTF8))
        self.btnStopVoice.setCheckable(False)
        self.btnStopVoice.setObjectName(_fromUtf8("btnStopVoice"))
        self.volumeSlider = phonon.Phonon.VolumeSlider(self.groupScene)
        self.volumeSlider.setGeometry(QtCore.QRect(350, 50, 91, 22))
        self.volumeSlider.setMaximumVolume(1.0)
        self.volumeSlider.setMuteVisible(True)
        self.volumeSlider.setObjectName(_fromUtf8("volumeSlider"))
        self.lstFiles = QtGui.QListWidget(self.centralwidget)
        self.lstFiles.setGeometry(QtCore.QRect(960, 60, 141, 512))
        self.lstFiles.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.lstFiles.setFrameShadow(QtGui.QFrame.Sunken)
        self.lstFiles.setAlternatingRowColors(True)
        self.lstFiles.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.lstFiles.setIconSize(QtCore.QSize(0, 0))
        self.lstFiles.setFlow(QtGui.QListView.TopToBottom)
        self.lstFiles.setLayoutMode(QtGui.QListView.SinglePass)
        self.lstFiles.setSpacing(0)
        self.lstFiles.setViewMode(QtGui.QListView.ListMode)
        self.lstFiles.setModelColumn(0)
        self.lstFiles.setSelectionRectVisible(False)
        self.lstFiles.setObjectName(_fromUtf8("lstFiles"))
        self.lblFolderName = QtGui.QLabel(self.centralwidget)
        self.lblFolderName.setGeometry(QtCore.QRect(960, 40, 141, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        self.lblFolderName.setFont(font)
        self.lblFolderName.setAutoFillBackground(False)
        self.lblFolderName.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblFolderName.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblFolderName.setLineWidth(1)
        self.lblFolderName.setMidLineWidth(0)
        self.lblFolderName.setText(_fromUtf8("script_pak_e08_0000.lin"))
        self.lblFolderName.setScaledContents(True)
        self.lblFolderName.setMargin(0)
        self.lblFolderName.setIndent(5)
        self.lblFolderName.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.lblFolderName.setObjectName(_fromUtf8("lblFolderName"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(1110, 10, 311, 562))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Meiryo UI"))
        font.setPointSize(11)
        self.groupBox.setFont(font)
        self.groupBox.setTitle(QtGui.QApplication.translate("Editor", "Related Files", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setCheckable(False)
        self.groupBox.setChecked(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.line_2 = QtGui.QFrame(self.groupBox)
        self.line_2.setGeometry(QtCore.QRect(10, 240, 291, 24))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label_14 = QtGui.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(10, 260, 141, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Meiryo UI"))
        font.setPointSize(9)
        self.label_14.setFont(font)
        self.label_14.setText(QtGui.QApplication.translate("Editor", "Translated", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.txtSimilarTrans = QtGui.QPlainTextEdit(self.groupBox)
        self.txtSimilarTrans.setGeometry(QtCore.QRect(10, 290, 291, 61))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtSimilarTrans.sizePolicy().hasHeightForWidth())
        self.txtSimilarTrans.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Meiryo UI"))
        font.setPointSize(10)
        self.txtSimilarTrans.setFont(font)
        self.txtSimilarTrans.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.txtSimilarTrans.setTabChangesFocus(True)
        self.txtSimilarTrans.setLineWrapMode(QtGui.QPlainTextEdit.WidgetWidth)
        self.txtSimilarTrans.setReadOnly(True)
        self.txtSimilarTrans.setPlainText(_fromUtf8(""))
        self.txtSimilarTrans.setObjectName(_fromUtf8("txtSimilarTrans"))
        self.txtSimilarOrig = QtGui.QPlainTextEdit(self.groupBox)
        self.txtSimilarOrig.setGeometry(QtCore.QRect(10, 390, 291, 61))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtSimilarOrig.sizePolicy().hasHeightForWidth())
        self.txtSimilarOrig.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Meiryo UI"))
        font.setPointSize(10)
        self.txtSimilarOrig.setFont(font)
        self.txtSimilarOrig.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.txtSimilarOrig.setTabChangesFocus(True)
        self.txtSimilarOrig.setLineWrapMode(QtGui.QPlainTextEdit.WidgetWidth)
        self.txtSimilarOrig.setReadOnly(True)
        self.txtSimilarOrig.setPlainText(_fromUtf8(""))
        self.txtSimilarOrig.setObjectName(_fromUtf8("txtSimilarOrig"))
        self.label_15 = QtGui.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(10, 360, 141, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Meiryo UI"))
        font.setPointSize(9)
        self.label_15.setFont(font)
        self.label_15.setText(QtGui.QApplication.translate("Editor", "Original", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.txtSimilarComm = QtGui.QPlainTextEdit(self.groupBox)
        self.txtSimilarComm.setGeometry(QtCore.QRect(10, 490, 291, 61))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtSimilarComm.sizePolicy().hasHeightForWidth())
        self.txtSimilarComm.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Meiryo UI"))
        font.setPointSize(10)
        self.txtSimilarComm.setFont(font)
        self.txtSimilarComm.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.txtSimilarComm.setTabChangesFocus(True)
        self.txtSimilarComm.setLineWrapMode(QtGui.QPlainTextEdit.WidgetWidth)
        self.txtSimilarComm.setReadOnly(True)
        self.txtSimilarComm.setPlainText(_fromUtf8(""))
        self.txtSimilarComm.setObjectName(_fromUtf8("txtSimilarComm"))
        self.label_16 = QtGui.QLabel(self.groupBox)
        self.label_16.setGeometry(QtCore.QRect(10, 460, 141, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Meiryo UI"))
        font.setPointSize(9)
        self.label_16.setFont(font)
        self.label_16.setText(QtGui.QApplication.translate("Editor", "Comments", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.tabRelated = QtGui.QTabWidget(self.groupBox)
        self.tabRelated.setGeometry(QtCore.QRect(10, 30, 291, 211))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        self.tabRelated.setFont(font)
        self.tabRelated.setAutoFillBackground(True)
        self.tabRelated.setObjectName(_fromUtf8("tabRelated"))
        self.tabDuplicates = QtGui.QWidget()
        self.tabDuplicates.setObjectName(_fromUtf8("tabDuplicates"))
        self.treeDupes = QtGui.QTreeWidget(self.tabDuplicates)
        self.treeDupes.setGeometry(QtCore.QRect(1, 1, 283, 183))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        self.treeDupes.setFont(font)
        self.treeDupes.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.treeDupes.setFrameShape(QtGui.QFrame.NoFrame)
        self.treeDupes.setAlternatingRowColors(True)
        self.treeDupes.setIndentation(15)
        self.treeDupes.setUniformRowHeights(True)
        self.treeDupes.setAnimated(True)
        self.treeDupes.setObjectName(_fromUtf8("treeDupes"))
        self.treeDupes.headerItem().setText(0, _fromUtf8("1"))
        self.treeDupes.header().setVisible(False)
        self.tabRelated.addTab(self.tabDuplicates, _fromUtf8(""))
        self.tabSimilar = QtGui.QWidget()
        self.tabSimilar.setObjectName(_fromUtf8("tabSimilar"))
        self.treeSimilar = QtGui.QTreeWidget(self.tabSimilar)
        self.treeSimilar.setGeometry(QtCore.QRect(1, 1, 283, 183))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        self.treeSimilar.setFont(font)
        self.treeSimilar.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.treeSimilar.setFrameShape(QtGui.QFrame.NoFrame)
        self.treeSimilar.setAlternatingRowColors(True)
        self.treeSimilar.setAutoExpandDelay(-1)
        self.treeSimilar.setIndentation(15)
        self.treeSimilar.setRootIsDecorated(True)
        self.treeSimilar.setUniformRowHeights(True)
        self.treeSimilar.setAnimated(True)
        self.treeSimilar.setAllColumnsShowFocus(False)
        self.treeSimilar.setColumnCount(1)
        self.treeSimilar.setObjectName(_fromUtf8("treeSimilar"))
        self.treeSimilar.headerItem().setText(0, _fromUtf8("Item"))
        self.treeSimilar.header().setVisible(False)
        self.treeSimilar.header().setCascadingSectionResizes(False)
        self.treeSimilar.header().setStretchLastSection(True)
        self.tabRelated.addTab(self.tabSimilar, _fromUtf8(""))
        self.tabReferences = QtGui.QWidget()
        self.tabReferences.setObjectName(_fromUtf8("tabReferences"))
        self.treeReferences = QtGui.QTreeWidget(self.tabReferences)
        self.treeReferences.setGeometry(QtCore.QRect(1, 1, 283, 183))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        self.treeReferences.setFont(font)
        self.treeReferences.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.treeReferences.setFrameShape(QtGui.QFrame.NoFrame)
        self.treeReferences.setAlternatingRowColors(True)
        self.treeReferences.setAutoExpandDelay(-1)
        self.treeReferences.setIndentation(15)
        self.treeReferences.setRootIsDecorated(True)
        self.treeReferences.setUniformRowHeights(True)
        self.treeReferences.setAnimated(True)
        self.treeReferences.setAllColumnsShowFocus(False)
        self.treeReferences.setColumnCount(1)
        self.treeReferences.setObjectName(_fromUtf8("treeReferences"))
        self.treeReferences.headerItem().setText(0, _fromUtf8("Item"))
        self.treeReferences.header().setVisible(False)
        self.treeReferences.header().setCascadingSectionResizes(False)
        self.treeReferences.header().setStretchLastSection(True)
        self.tabRelated.addTab(self.tabReferences, _fromUtf8(""))
        self.btnCollapseAll = QtGui.QPushButton(self.groupBox)
        self.btnCollapseAll.setGeometry(QtCore.QRect(279, 30, 21, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        self.btnCollapseAll.setFont(font)
        self.btnCollapseAll.setText(QtGui.QApplication.translate("Editor", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCollapseAll.setObjectName(_fromUtf8("btnCollapseAll"))
        self.btnExpandAll = QtGui.QPushButton(self.groupBox)
        self.btnExpandAll.setGeometry(QtCore.QRect(260, 30, 21, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        self.btnExpandAll.setFont(font)
        self.btnExpandAll.setText(QtGui.QApplication.translate("Editor", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.btnExpandAll.setObjectName(_fromUtf8("btnExpandAll"))
        self.tabsOriginal = QtGui.QTabWidget(self.centralwidget)
        self.tabsOriginal.setGeometry(QtCore.QRect(500, 330, 451, 101))
        self.tabsOriginal.setTabPosition(QtGui.QTabWidget.North)
        self.tabsOriginal.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabsOriginal.setElideMode(QtCore.Qt.ElideNone)
        self.tabsOriginal.setMovable(False)
        self.tabsOriginal.setObjectName(_fromUtf8("tabsOriginal"))
        self.tabOrig = QtGui.QWidget()
        self.tabOrig.setObjectName(_fromUtf8("tabOrig"))
        self.txtOriginal = KeywordEdit(self.tabOrig)
        self.txtOriginal.setEnabled(True)
        self.txtOriginal.setGeometry(QtCore.QRect(-1, -1, 447, 77))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Meiryo UI"))
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.txtOriginal.setFont(font)
        self.txtOriginal.setToolTip(_fromUtf8(""))
        self.txtOriginal.setReadOnly(True)
        self.txtOriginal.setHtml(QtGui.QApplication.translate("Editor", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Meiryo UI\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.txtOriginal.setTabStopWidth(20)
        self.txtOriginal.setObjectName(_fromUtf8("txtOriginal"))
        self.tabsOriginal.addTab(self.tabOrig, _fromUtf8(""))
        self.tabNoTags = QtGui.QWidget()
        self.tabNoTags.setObjectName(_fromUtf8("tabNoTags"))
        self.txtOriginalNoTags = QtGui.QPlainTextEdit(self.tabNoTags)
        self.txtOriginalNoTags.setEnabled(True)
        self.txtOriginalNoTags.setGeometry(QtCore.QRect(-1, -1, 447, 77))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Meiryo UI"))
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.txtOriginalNoTags.setFont(font)
        self.txtOriginalNoTags.setTabChangesFocus(True)
        self.txtOriginalNoTags.setReadOnly(True)
        self.txtOriginalNoTags.setPlainText(_fromUtf8(""))
        self.txtOriginalNoTags.setTabStopWidth(20)
        self.txtOriginalNoTags.setObjectName(_fromUtf8("txtOriginalNoTags"))
        self.tabsOriginal.addTab(self.tabNoTags, _fromUtf8(""))
        self.tabHide = QtGui.QWidget()
        self.tabHide.setObjectName(_fromUtf8("tabHide"))
        self.tabsOriginal.addTab(self.tabHide, _fromUtf8(""))
        self.btnCopyFromOrig = QtGui.QPushButton(self.centralwidget)
        self.btnCopyFromOrig.setGeometry(QtCore.QRect(851, 20, 101, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        self.btnCopyFromOrig.setFont(font)
        self.btnCopyFromOrig.setText(QtGui.QApplication.translate("Editor", "Copy from Original", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCopyFromOrig.setCheckable(False)
        self.btnCopyFromOrig.setObjectName(_fromUtf8("btnCopyFromOrig"))
        self.btnAddQuotes = QtGui.QPushButton(self.centralwidget)
        self.btnAddQuotes.setGeometry(QtCore.QRect(741, 20, 22, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(10)
        font.setKerning(True)
        self.btnAddQuotes.setFont(font)
        self.btnAddQuotes.setToolTip(QtGui.QApplication.translate("Editor", "Double Quotes", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddQuotes.setText(QtGui.QApplication.translate("Editor", "“”", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddQuotes.setShortcut(QtGui.QApplication.translate("Editor", "Ctrl+\'", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddQuotes.setCheckable(False)
        self.btnAddQuotes.setObjectName(_fromUtf8("btnAddQuotes"))
        self.btnAddDash = QtGui.QPushButton(self.centralwidget)
        self.btnAddDash.setGeometry(QtCore.QRect(699, 20, 22, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(10)
        font.setKerning(True)
        self.btnAddDash.setFont(font)
        self.btnAddDash.setToolTip(QtGui.QApplication.translate("Editor", "Em Dash", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddDash.setText(QtGui.QApplication.translate("Editor", "―", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddDash.setShortcut(QtGui.QApplication.translate("Editor", "Ctrl+Shift+_", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddDash.setCheckable(False)
        self.btnAddDash.setObjectName(_fromUtf8("btnAddDash"))
        self.btnAddClt = SuperButton(self.centralwidget)
        self.btnAddClt.setGeometry(QtCore.QRect(783, 20, 31, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        font.setKerning(True)
        self.btnAddClt.setFont(font)
        self.btnAddClt.setText(QtGui.QApplication.translate("Editor", "CLT", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddClt.setShortcut(QtGui.QApplication.translate("Editor", "Alt+C", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddClt.setCheckable(False)
        self.btnAddClt.setObjectName(_fromUtf8("btnAddClt"))
        self.spnClt = QtGui.QSpinBox(self.centralwidget)
        self.spnClt.setGeometry(QtCore.QRect(815, 21, 36, 18))
        self.spnClt.setFrame(True)
        self.spnClt.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.spnClt.setMaximum(91)
        self.spnClt.setObjectName(_fromUtf8("spnClt"))
        self.btnAddBrackets = QtGui.QPushButton(self.centralwidget)
        self.btnAddBrackets.setGeometry(QtCore.QRect(762, 20, 22, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(10)
        font.setKerning(True)
        self.btnAddBrackets.setFont(font)
        self.btnAddBrackets.setToolTip(QtGui.QApplication.translate("Editor", "Reaction Talk Brackets", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddBrackets.setStyleSheet(_fromUtf8("padding-left: 2px;"))
        self.btnAddBrackets.setText(QtGui.QApplication.translate("Editor", "【】", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddBrackets.setShortcut(QtGui.QApplication.translate("Editor", "Ctrl+[, Ctrl+]", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddBrackets.setCheckable(False)
        self.btnAddBrackets.setObjectName(_fromUtf8("btnAddBrackets"))
        self.btnAddSingleQuotes = QtGui.QPushButton(self.centralwidget)
        self.btnAddSingleQuotes.setGeometry(QtCore.QRect(720, 20, 22, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(10)
        font.setKerning(True)
        self.btnAddSingleQuotes.setFont(font)
        self.btnAddSingleQuotes.setToolTip(QtGui.QApplication.translate("Editor", "Single Quotes", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddSingleQuotes.setText(QtGui.QApplication.translate("Editor", "‘’", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddSingleQuotes.setShortcut(QtGui.QApplication.translate("Editor", "Ctrl+\'", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddSingleQuotes.setCheckable(False)
        self.btnAddSingleQuotes.setObjectName(_fromUtf8("btnAddSingleQuotes"))
        self.btnAddEnDash = QtGui.QPushButton(self.centralwidget)
        self.btnAddEnDash.setGeometry(QtCore.QRect(678, 20, 22, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(10)
        font.setKerning(True)
        self.btnAddEnDash.setFont(font)
        self.btnAddEnDash.setToolTip(QtGui.QApplication.translate("Editor", "En Dash", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddEnDash.setText(QtGui.QApplication.translate("Editor", "–", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddEnDash.setShortcut(QtGui.QApplication.translate("Editor", "Ctrl+-", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddEnDash.setCheckable(False)
        self.btnAddEnDash.setObjectName(_fromUtf8("btnAddEnDash"))
        Editor.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(Editor)
        self.statusbar.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        self.statusbar.setMaximumSize(QtCore.QSize(65536, 65536))
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Editor.setStatusBar(self.statusbar)
        self.menubar = QtGui.QMenuBar(Editor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1430, 24))
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setTitle(QtGui.QApplication.translate("Editor", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setTitle(QtGui.QApplication.translate("Editor", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setTitle(QtGui.QApplication.translate("Editor", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setTitle(QtGui.QApplication.translate("Editor", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setTitle(QtGui.QApplication.translate("Editor", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        self.menuImportExport = QtGui.QMenu(self.menuTools)
        self.menuImportExport.setTitle(QtGui.QApplication.translate("Editor", "&Import/Export", None, QtGui.QApplication.UnicodeUTF8))
        self.menuImportExport.setObjectName(_fromUtf8("menuImportExport"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setTitle(QtGui.QApplication.translate("Editor", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setObjectName(_fromUtf8("menuView"))
        Editor.setMenuBar(self.menubar)
        self.toolBar = QtGui.QToolBar(Editor)
        self.toolBar.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("Editor", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.toolBar.setMovable(False)
        self.toolBar.setAllowedAreas(QtCore.Qt.TopToolBarArea)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        Editor.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen = QtGui.QAction(Editor)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/folder.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon1)
        self.actionOpen.setText(QtGui.QApplication.translate("Editor", "&Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("Editor", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(Editor)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/disk.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon2)
        self.actionSave.setText(QtGui.QApplication.translate("Editor", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setShortcut(QtGui.QApplication.translate("Editor", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionExit = QtGui.QAction(Editor)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/cross.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon3)
        self.actionExit.setText(QtGui.QApplication.translate("Editor", "E&xit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionAbout = QtGui.QAction(Editor)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/help.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon4)
        self.actionAbout.setText(QtGui.QApplication.translate("Editor", "&About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setIconText(QtGui.QApplication.translate("Editor", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionInsertLine = QtGui.QAction(Editor)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/new.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInsertLine.setIcon(icon5)
        self.actionInsertLine.setText(QtGui.QApplication.translate("Editor", "&Insert line after selection", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInsertLine.setIconText(QtGui.QApplication.translate("Editor", "Insert Line", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInsertLine.setObjectName(_fromUtf8("actionInsertLine"))
        self.actionShowPrefs = QtGui.QAction(Editor)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/wrench.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShowPrefs.setIcon(icon6)
        self.actionShowPrefs.setText(QtGui.QApplication.translate("Editor", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowPrefs.setIconText(QtGui.QApplication.translate("Editor", "File Locs", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowPrefs.setObjectName(_fromUtf8("actionShowPrefs"))
        self.actionSearch = QtGui.QAction(Editor)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/magnifier.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSearch.setIcon(icon7)
        self.actionSearch.setText(QtGui.QApplication.translate("Editor", "&Search...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSearch.setShortcut(QtGui.QApplication.translate("Editor", "Ctrl+F", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSearch.setObjectName(_fromUtf8("actionSearch"))
        self.actionBuild = QtGui.QAction(Editor)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/cog_go.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBuild.setIcon(icon8)
        self.actionBuild.setText(QtGui.QApplication.translate("Editor", "&Build Archives && ISO", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBuild.setIconText(QtGui.QApplication.translate("Editor", "Build", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBuild.setToolTip(QtGui.QApplication.translate("Editor", "Build Archives & ISO", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBuild.setShortcut(QtGui.QApplication.translate("Editor", "Ctrl+B", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBuild.setObjectName(_fromUtf8("actionBuild"))
        self.actionTerminology = QtGui.QAction(Editor)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/book.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTerminology.setIcon(icon9)
        self.actionTerminology.setText(QtGui.QApplication.translate("Editor", "&Terminology Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTerminology.setIconText(QtGui.QApplication.translate("Editor", "Terms", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTerminology.setShortcut(QtGui.QApplication.translate("Editor", "Ctrl+T", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTerminology.setObjectName(_fromUtf8("actionTerminology"))
        self.actionHighlightTerminology = QtGui.QAction(Editor)
        self.actionHighlightTerminology.setCheckable(True)
        self.actionHighlightTerminology.setChecked(True)
        self.actionHighlightTerminology.setText(QtGui.QApplication.translate("Editor", "Highlight Terminology", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHighlightTerminology.setShortcut(QtGui.QApplication.translate("Editor", "Alt+H", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHighlightTerminology.setObjectName(_fromUtf8("actionHighlightTerminology"))
        self.actionNextFile = QtGui.QAction(Editor)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/resultset_next.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNextFile.setIcon(icon10)
        self.actionNextFile.setText(QtGui.QApplication.translate("Editor", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNextFile.setIconText(QtGui.QApplication.translate("Editor", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNextFile.setShortcut(QtGui.QApplication.translate("Editor", "PgDown", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNextFile.setObjectName(_fromUtf8("actionNextFile"))
        self.actionPreviousFile = QtGui.QAction(Editor)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/resultset_previous.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPreviousFile.setIcon(icon11)
        self.actionPreviousFile.setText(QtGui.QApplication.translate("Editor", "Previous", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreviousFile.setIconText(QtGui.QApplication.translate("Editor", "Prev", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreviousFile.setShortcut(QtGui.QApplication.translate("Editor", "PgUp", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreviousFile.setObjectName(_fromUtf8("actionPreviousFile"))
        self.actionAutoExpand = QtGui.QAction(Editor)
        self.actionAutoExpand.setCheckable(True)
        self.actionAutoExpand.setChecked(True)
        self.actionAutoExpand.setText(QtGui.QApplication.translate("Editor", "Auto-Expand Similarity Trees", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAutoExpand.setShortcut(QtGui.QApplication.translate("Editor", "Alt+T", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAutoExpand.setObjectName(_fromUtf8("actionAutoExpand"))
        self.actionCopyOrig = QtGui.QAction(Editor)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/page_copy.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopyOrig.setIcon(icon12)
        self.actionCopyOrig.setText(QtGui.QApplication.translate("Editor", "Copy Original to Translated", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopyOrig.setShortcut(QtGui.QApplication.translate("Editor", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopyOrig.setObjectName(_fromUtf8("actionCopyOrig"))
        self.actionAutoPlayVoice = QtGui.QAction(Editor)
        self.actionAutoPlayVoice.setCheckable(True)
        self.actionAutoPlayVoice.setChecked(True)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/sound_mute.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/sound.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionAutoPlayVoice.setIcon(icon13)
        self.actionAutoPlayVoice.setText(QtGui.QApplication.translate("Editor", "Auto-Play Voice Files", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAutoPlayVoice.setIconText(QtGui.QApplication.translate("Editor", "Voice", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAutoPlayVoice.setShortcut(QtGui.QApplication.translate("Editor", "Ctrl+Alt+V", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAutoPlayVoice.setIconVisibleInMenu(True)
        self.actionAutoPlayVoice.setObjectName(_fromUtf8("actionAutoPlayVoice"))
        self.actionReloadDirectory = QtGui.QAction(Editor)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/arrow_refresh.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReloadDirectory.setIcon(icon14)
        self.actionReloadDirectory.setText(QtGui.QApplication.translate("Editor", "Reload Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReloadDirectory.setIconText(QtGui.QApplication.translate("Editor", "Reload", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReloadDirectory.setShortcut(QtGui.QApplication.translate("Editor", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReloadDirectory.setObjectName(_fromUtf8("actionReloadDirectory"))
        self.actionShowDirectory = QtGui.QAction(Editor)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/folder_explore.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShowDirectory.setIcon(icon15)
        self.actionShowDirectory.setText(QtGui.QApplication.translate("Editor", "Show in Explorer", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowDirectory.setIconText(QtGui.QApplication.translate("Editor", "Show Dir", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowDirectory.setShortcut(QtGui.QApplication.translate("Editor", "Alt+D", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowDirectory.setObjectName(_fromUtf8("actionShowDirectory"))
        self.actionCalculateProgress = QtGui.QAction(Editor)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/chart_bar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCalculateProgress.setIcon(icon16)
        self.actionCalculateProgress.setText(QtGui.QApplication.translate("Editor", "Calculate Progress", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCalculateProgress.setIconText(QtGui.QApplication.translate("Editor", "Progress", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCalculateProgress.setObjectName(_fromUtf8("actionCalculateProgress"))
        self.actionImportData01 = QtGui.QAction(Editor)
        self.actionImportData01.setText(QtGui.QApplication.translate("Editor", "Import to data01", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImportData01.setObjectName(_fromUtf8("actionImportData01"))
        self.actionImportUmdimage2 = QtGui.QAction(Editor)
        self.actionImportUmdimage2.setText(QtGui.QApplication.translate("Editor", "...to umdimage2", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImportUmdimage2.setObjectName(_fromUtf8("actionImportUmdimage2"))
        self.actionImportOther = QtGui.QAction(Editor)
        self.actionImportOther.setText(QtGui.QApplication.translate("Editor", "...to other directory", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImportOther.setObjectName(_fromUtf8("actionImportOther"))
        self.actionExportChanges = QtGui.QAction(Editor)
        self.actionExportChanges.setText(QtGui.QApplication.translate("Editor", "Export Changes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportChanges.setObjectName(_fromUtf8("actionExportChanges"))
        self.actionReloadDupesDB = QtGui.QAction(Editor)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/database_refresh.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReloadDupesDB.setIcon(icon17)
        self.actionReloadDupesDB.setText(QtGui.QApplication.translate("Editor", "Reload &Dupes DB", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReloadDupesDB.setShortcut(QtGui.QApplication.translate("Editor", "Ctrl+D", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReloadDupesDB.setObjectName(_fromUtf8("actionReloadDupesDB"))
        self.actionCheckForErrors = QtGui.QAction(Editor)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8(":/report.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCheckForErrors.setIcon(icon18)
        self.actionCheckForErrors.setText(QtGui.QApplication.translate("Editor", "&Check for Errors", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCheckForErrors.setIconText(QtGui.QApplication.translate("Editor", "Errors", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCheckForErrors.setToolTip(QtGui.QApplication.translate("Editor", "Check for errors in the script", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCheckForErrors.setObjectName(_fromUtf8("actionCheckForErrors"))
        self.actionFirstFile = QtGui.QAction(Editor)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8(":/resultset_first.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFirstFile.setIcon(icon19)
        self.actionFirstFile.setText(QtGui.QApplication.translate("Editor", "First", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFirstFile.setShortcut(QtGui.QApplication.translate("Editor", "Ctrl+PgUp", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFirstFile.setObjectName(_fromUtf8("actionFirstFile"))
        self.actionLastFile = QtGui.QAction(Editor)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8(":/resultset_last.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLastFile.setIcon(icon20)
        self.actionLastFile.setText(QtGui.QApplication.translate("Editor", "Last", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLastFile.setShortcut(QtGui.QApplication.translate("Editor", "Ctrl+PgDown", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLastFile.setObjectName(_fromUtf8("actionLastFile"))
        self.actionAutoPlayBGM = QtGui.QAction(Editor)
        self.actionAutoPlayBGM.setCheckable(True)
        self.actionAutoPlayBGM.setChecked(True)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(_fromUtf8(":/sound_none.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon21.addPixmap(QtGui.QPixmap(_fromUtf8(":/sound.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionAutoPlayBGM.setIcon(icon21)
        self.actionAutoPlayBGM.setText(QtGui.QApplication.translate("Editor", "Auto-Play BGM Files", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAutoPlayBGM.setIconText(QtGui.QApplication.translate("Editor", "BGM", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAutoPlayBGM.setToolTip(QtGui.QApplication.translate("Editor", "Auto-Play BGM Files", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAutoPlayBGM.setShortcut(QtGui.QApplication.translate("Editor", "Ctrl+Alt+B", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAutoPlayBGM.setIconVisibleInMenu(True)
        self.actionAutoPlayBGM.setObjectName(_fromUtf8("actionAutoPlayBGM"))
        self.actionFontGenerator = QtGui.QAction(Editor)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(_fromUtf8(":/font.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFontGenerator.setIcon(icon22)
        self.actionFontGenerator.setText(QtGui.QApplication.translate("Editor", "Font Generator", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFontGenerator.setObjectName(_fromUtf8("actionFontGenerator"))
        self.actionConsole = QtGui.QAction(Editor)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(_fromUtf8(":/application_xp_terminal.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConsole.setIcon(icon23)
        self.actionConsole.setText(QtGui.QApplication.translate("Editor", "Console", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConsole.setObjectName(_fromUtf8("actionConsole"))
        self.actionInsertCLT = QtGui.QAction(Editor)
        self.actionInsertCLT.setText(QtGui.QApplication.translate("Editor", "Insert CLT", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInsertCLT.setShortcut(QtGui.QApplication.translate("Editor", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInsertCLT.setObjectName(_fromUtf8("actionInsertCLT"))
        self.actionDecompile_All_wrd_Files = QtGui.QAction(Editor)
        self.actionDecompile_All_wrd_Files.setText(QtGui.QApplication.translate("Editor", "Decompile All wrd Files", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDecompile_All_wrd_Files.setObjectName(_fromUtf8("actionDecompile_All_wrd_Files"))
        self.actionCompile_All_wrd_Files = QtGui.QAction(Editor)
        self.actionCompile_All_wrd_Files.setText(QtGui.QApplication.translate("Editor", "Compile All wrd Files", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCompile_All_wrd_Files.setObjectName(_fromUtf8("actionCompile_All_wrd_Files"))
        self.actionScriptDumper = QtGui.QAction(Editor)
        self.actionScriptDumper.setText(QtGui.QApplication.translate("Editor", "Script Dumper", None, QtGui.QApplication.UnicodeUTF8))
        self.actionScriptDumper.setObjectName(_fromUtf8("actionScriptDumper"))
        self.actionConvertPNGGIM = QtGui.QAction(Editor)
        self.actionConvertPNGGIM.setCheckable(True)
        self.actionConvertPNGGIM.setChecked(True)
        self.actionConvertPNGGIM.setText(QtGui.QApplication.translate("Editor", "Convert PNG ↔ GIM", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConvertPNGGIM.setObjectName(_fromUtf8("actionConvertPNGGIM"))
        self.actionConvert_GIM_to_PNG = QtGui.QAction(Editor)
        self.actionConvert_GIM_to_PNG.setCheckable(True)
        self.actionConvert_GIM_to_PNG.setChecked(True)
        self.actionConvert_GIM_to_PNG.setText(QtGui.QApplication.translate("Editor", "Convert GIM to PNG", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConvert_GIM_to_PNG.setObjectName(_fromUtf8("actionConvert_GIM_to_PNG"))
        self.actionExportData01 = QtGui.QAction(Editor)
        self.actionExportData01.setText(QtGui.QApplication.translate("Editor", "Export from data01", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportData01.setObjectName(_fromUtf8("actionExportData01"))
        self.actionExportUmdimage2 = QtGui.QAction(Editor)
        self.actionExportUmdimage2.setText(QtGui.QApplication.translate("Editor", "...from umdimage2", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportUmdimage2.setObjectName(_fromUtf8("actionExportUmdimage2"))
        self.actionExtractTextures = QtGui.QAction(Editor)
        self.actionExtractTextures.setCheckable(True)
        self.actionExtractTextures.setChecked(True)
        self.actionExtractTextures.setText(QtGui.QApplication.translate("Editor", "Extract/insert textures", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExtractTextures.setObjectName(_fromUtf8("actionExtractTextures"))
        self.actionExportUnique = QtGui.QAction(Editor)
        self.actionExportUnique.setCheckable(True)
        self.actionExportUnique.setText(QtGui.QApplication.translate("Editor", "Only export unique", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportUnique.setObjectName(_fromUtf8("actionExportUnique"))
        self.actionPropogateDupes = QtGui.QAction(Editor)
        self.actionPropogateDupes.setCheckable(True)
        self.actionPropogateDupes.setChecked(True)
        self.actionPropogateDupes.setText(QtGui.QApplication.translate("Editor", "Propogate dupes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPropogateDupes.setObjectName(_fromUtf8("actionPropogateDupes"))
        self.actionGoToReference = QtGui.QAction(Editor)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(_fromUtf8(":/folder_go.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGoToReference.setIcon(icon24)
        self.actionGoToReference.setText(QtGui.QApplication.translate("Editor", "Go To Reference", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGoToReference.setShortcut(QtGui.QApplication.translate("Editor", "Ctrl+G", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGoToReference.setObjectName(_fromUtf8("actionGoToReference"))
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionGoToReference)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuSettings.addAction(self.actionShowPrefs)
        self.menuEdit.addAction(self.actionInsertCLT)
        self.menuEdit.addAction(self.actionSearch)
        self.menuEdit.addAction(self.actionCopyOrig)
        self.menuImportExport.addAction(self.actionConvertPNGGIM)
        self.menuImportExport.addAction(self.actionPropogateDupes)
        self.menuImportExport.addAction(self.actionExportUnique)
        self.menuImportExport.addSeparator()
        self.menuImportExport.addAction(self.actionImportData01)
        self.menuImportExport.addAction(self.actionExportData01)
        self.menuTools.addAction(self.menuImportExport.menuAction())
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionFontGenerator)
        self.menuTools.addAction(self.actionTerminology)
        self.menuTools.addAction(self.actionScriptDumper)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionCalculateProgress)
        self.menuTools.addAction(self.actionCheckForErrors)
        self.menuTools.addAction(self.actionReloadDupesDB)
        self.menuTools.addAction(self.actionBuild)
        self.menuView.addAction(self.actionFirstFile)
        self.menuView.addAction(self.actionPreviousFile)
        self.menuView.addAction(self.actionNextFile)
        self.menuView.addAction(self.actionLastFile)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionShowDirectory)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionConsole)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionReloadDirectory)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionShowDirectory)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionFirstFile)
        self.toolBar.addAction(self.actionPreviousFile)
        self.toolBar.addAction(self.actionNextFile)
        self.toolBar.addAction(self.actionLastFile)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionTerminology)
        self.toolBar.addAction(self.actionAutoPlayVoice)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionInsertLine)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSearch)

        self.retranslateUi(Editor)
        self.tabRelated.setCurrentIndex(0)
        self.tabsOriginal.setCurrentIndex(0)
        QtCore.QObject.connect(self.lstFiles, QtCore.SIGNAL(_fromUtf8("currentRowChanged(int)")), Editor.changedScriptFile)
        QtCore.QObject.connect(self.treeDupes, QtCore.SIGNAL(_fromUtf8("currentItemChanged(QTreeWidgetItem*,QTreeWidgetItem*)")), Editor.changedDupe)
        QtCore.QObject.connect(self.treeSimilar, QtCore.SIGNAL(_fromUtf8("currentItemChanged(QTreeWidgetItem*,QTreeWidgetItem*)")), Editor.changedSimilar)
        QtCore.QObject.connect(self.txtTranslated, QtCore.SIGNAL(_fromUtf8("textChanged()")), Editor.changedTranslated)
        QtCore.QObject.connect(self.txtComments, QtCore.SIGNAL(_fromUtf8("textChanged()")), Editor.changedComments)
        QtCore.QObject.connect(self.btnExpandAll, QtCore.SIGNAL(_fromUtf8("clicked()")), Editor.expandAll)
        QtCore.QObject.connect(self.btnCollapseAll, QtCore.SIGNAL(_fromUtf8("clicked()")), Editor.collapseAll)
        QtCore.QObject.connect(self.btnCopyFromOrig, QtCore.SIGNAL(_fromUtf8("clicked()")), Editor.copyFromOrig)
        QtCore.QObject.connect(self.treeReferences, QtCore.SIGNAL(_fromUtf8("currentItemChanged(QTreeWidgetItem*,QTreeWidgetItem*)")), Editor.changedReference)
        QtCore.QObject.connect(self.txtTranslated, QtCore.SIGNAL(_fromUtf8("cursorPositionChanged()")), Editor.updateStatusCursor)
        QtCore.QObject.connect(self.tabsOriginal, QtCore.SIGNAL(_fromUtf8("currentChanged(int)")), Editor.changedOriginalTab)
        QtCore.QObject.connect(self.txtOriginal, QtCore.SIGNAL(_fromUtf8("textChanged()")), Editor.changedOriginal)
        QtCore.QObject.connect(self.btnStopVoice, QtCore.SIGNAL(_fromUtf8("clicked()")), Editor.stopVoice)
        QtCore.QObject.connect(self.btnPlayVoice, QtCore.SIGNAL(_fromUtf8("clicked()")), Editor.playVoice)
        QtCore.QMetaObject.connectSlotsByName(Editor)
        Editor.setTabOrder(self.txtTranslated, self.btnAddEnDash)
        Editor.setTabOrder(self.btnAddEnDash, self.btnAddDash)
        Editor.setTabOrder(self.btnAddDash, self.btnAddSingleQuotes)
        Editor.setTabOrder(self.btnAddSingleQuotes, self.btnAddQuotes)
        Editor.setTabOrder(self.btnAddQuotes, self.btnAddBrackets)
        Editor.setTabOrder(self.btnAddBrackets, self.btnAddClt)
        Editor.setTabOrder(self.btnAddClt, self.spnClt)
        Editor.setTabOrder(self.spnClt, self.btnCopyFromOrig)
        Editor.setTabOrder(self.btnCopyFromOrig, self.btnPlayVoice)
        Editor.setTabOrder(self.btnPlayVoice, self.btnStopVoice)
        Editor.setTabOrder(self.btnStopVoice, self.tabsOriginal)
        Editor.setTabOrder(self.tabsOriginal, self.txtOriginal)
        Editor.setTabOrder(self.txtOriginal, self.txtOriginalNoTags)
        Editor.setTabOrder(self.txtOriginalNoTags, self.txtComments)
        Editor.setTabOrder(self.txtComments, self.lstFiles)
        Editor.setTabOrder(self.lstFiles, self.tabRelated)
        Editor.setTabOrder(self.tabRelated, self.btnExpandAll)
        Editor.setTabOrder(self.btnExpandAll, self.btnCollapseAll)
        Editor.setTabOrder(self.btnCollapseAll, self.treeDupes)
        Editor.setTabOrder(self.treeDupes, self.treeSimilar)
        Editor.setTabOrder(self.treeSimilar, self.treeReferences)
        Editor.setTabOrder(self.treeReferences, self.txtSimilarTrans)
        Editor.setTabOrder(self.txtSimilarTrans, self.txtSimilarOrig)
        Editor.setTabOrder(self.txtSimilarOrig, self.txtSimilarComm)

    def retranslateUi(self, Editor):
        self.tabRelated.setTabText(self.tabRelated.indexOf(self.tabDuplicates), QtGui.QApplication.translate("Editor", "0 Dupes", None, QtGui.QApplication.UnicodeUTF8))
        self.treeSimilar.setSortingEnabled(False)
        self.tabRelated.setTabText(self.tabRelated.indexOf(self.tabSimilar), QtGui.QApplication.translate("Editor", "0 Similar", None, QtGui.QApplication.UnicodeUTF8))
        self.treeReferences.setSortingEnabled(False)
        self.tabRelated.setTabText(self.tabRelated.indexOf(self.tabReferences), QtGui.QApplication.translate("Editor", "0 References", None, QtGui.QApplication.UnicodeUTF8))
        self.tabsOriginal.setTabText(self.tabsOriginal.indexOf(self.tabOrig), QtGui.QApplication.translate("Editor", "Original", None, QtGui.QApplication.UnicodeUTF8))
        self.tabsOriginal.setTabText(self.tabsOriginal.indexOf(self.tabNoTags), QtGui.QApplication.translate("Editor", "No Tags", None, QtGui.QApplication.UnicodeUTF8))
        self.tabsOriginal.setTabText(self.tabsOriginal.indexOf(self.tabHide), QtGui.QApplication.translate("Editor", "Hide", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import phonon
from reference_edit import ReferenceEdit
from keyword_edit import KeywordEdit
from super_button import SuperButton
from smart_text_edit import SmartTextEdit
import icons_rc
