# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt\ui\settingsmenu.ui'
#
# Created: Tue Jul 16 17:26:48 2013
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_SettingsMenu(object):
    def setupUi(self, SettingsMenu):
        SettingsMenu.setObjectName(_fromUtf8("SettingsMenu"))
        SettingsMenu.resize(462, 372)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SettingsMenu.sizePolicy().hasHeightForWidth())
        SettingsMenu.setSizePolicy(sizePolicy)
        SettingsMenu.setWindowTitle(QtGui.QApplication.translate("SettingsMenu", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/monokuma-green.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SettingsMenu.setWindowIcon(icon)
        SettingsMenu.setStyleSheet(_fromUtf8(""))
        self.verticalLayout = QtGui.QVBoxLayout(SettingsMenu)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(SettingsMenu)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet(_fromUtf8(""))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabPrefs = QtGui.QWidget()
        self.tabPrefs.setObjectName(_fromUtf8("tabPrefs"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabPrefs)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox = QtGui.QGroupBox(self.tabPrefs)
        self.groupBox.setTitle(QtGui.QApplication.translate("SettingsMenu", "Playback", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setContentsMargins(-1, 4, -1, 7)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.chkPlayVoices = QtGui.QCheckBox(self.groupBox)
        self.chkPlayVoices.setText(QtGui.QApplication.translate("SettingsMenu", "Voices", None, QtGui.QApplication.UnicodeUTF8))
        self.chkPlayVoices.setChecked(True)
        self.chkPlayVoices.setObjectName(_fromUtf8("chkPlayVoices"))
        self.horizontalLayout_3.addWidget(self.chkPlayVoices)
        self.chkPlayBGM = QtGui.QCheckBox(self.groupBox)
        self.chkPlayBGM.setEnabled(False)
        self.chkPlayBGM.setText(QtGui.QApplication.translate("SettingsMenu", "BGM", None, QtGui.QApplication.UnicodeUTF8))
        self.chkPlayBGM.setObjectName(_fromUtf8("chkPlayBGM"))
        self.horizontalLayout_3.addWidget(self.chkPlayBGM)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.tabPrefs)
        self.groupBox_2.setTitle(QtGui.QApplication.translate("SettingsMenu", "Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_7.setContentsMargins(-1, 4, -1, 8)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.chkSpellCheck = QtGui.QCheckBox(self.groupBox_2)
        self.chkSpellCheck.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkSpellCheck.sizePolicy().hasHeightForWidth())
        self.chkSpellCheck.setSizePolicy(sizePolicy)
        self.chkSpellCheck.setText(QtGui.QApplication.translate("SettingsMenu", "Spellcheck", None, QtGui.QApplication.UnicodeUTF8))
        self.chkSpellCheck.setChecked(True)
        self.chkSpellCheck.setObjectName(_fromUtf8("chkSpellCheck"))
        self.horizontalLayout.addWidget(self.chkSpellCheck)
        self.cboSpellCheckLang = QtGui.QComboBox(self.groupBox_2)
        self.cboSpellCheckLang.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboSpellCheckLang.sizePolicy().hasHeightForWidth())
        self.cboSpellCheckLang.setSizePolicy(sizePolicy)
        self.cboSpellCheckLang.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.cboSpellCheckLang.setObjectName(_fromUtf8("cboSpellCheckLang"))
        self.cboSpellCheckLang.addItem(_fromUtf8(""))
        self.cboSpellCheckLang.setItemText(0, QtGui.QApplication.translate("SettingsMenu", "English (US)", None, QtGui.QApplication.UnicodeUTF8))
        self.cboSpellCheckLang.addItem(_fromUtf8(""))
        self.cboSpellCheckLang.setItemText(1, QtGui.QApplication.translate("SettingsMenu", "English (UK)", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout.addWidget(self.cboSpellCheckLang)
        self.verticalLayout_9.addLayout(self.horizontalLayout)
        self.chkTextRepl = QtGui.QCheckBox(self.groupBox_2)
        self.chkTextRepl.setEnabled(True)
        self.chkTextRepl.setText(QtGui.QApplication.translate("SettingsMenu", "Automatic text replacement", None, QtGui.QApplication.UnicodeUTF8))
        self.chkTextRepl.setObjectName(_fromUtf8("chkTextRepl"))
        self.verticalLayout_9.addWidget(self.chkTextRepl)
        self.chkSmartQuotes = QtGui.QCheckBox(self.groupBox_2)
        self.chkSmartQuotes.setEnabled(True)
        self.chkSmartQuotes.setToolTip(QtGui.QApplication.translate("SettingsMenu", "Automatically replaces straight apostrophes and quotes with angled versions.", None, QtGui.QApplication.UnicodeUTF8))
        self.chkSmartQuotes.setText(QtGui.QApplication.translate("SettingsMenu", "Smart quotes", None, QtGui.QApplication.UnicodeUTF8))
        self.chkSmartQuotes.setObjectName(_fromUtf8("chkSmartQuotes"))
        self.verticalLayout_9.addWidget(self.chkSmartQuotes)
        self.chkQuickClt = QtGui.QCheckBox(self.groupBox_2)
        self.chkQuickClt.setToolTip(QtGui.QApplication.translate("SettingsMenu", "Automatically replaces <X> with <CLT X>[cursor]<CLT> or <CLT><CLT X>[cursor] if there\'s an active CLT at the cursor.", None, QtGui.QApplication.UnicodeUTF8))
        self.chkQuickClt.setText(QtGui.QApplication.translate("SettingsMenu", "Quick CLT", None, QtGui.QApplication.UnicodeUTF8))
        self.chkQuickClt.setObjectName(_fromUtf8("chkQuickClt"))
        self.verticalLayout_9.addWidget(self.chkQuickClt)
        self.chkMangle = QtGui.QCheckBox(self.groupBox_2)
        self.chkMangle.setText(QtGui.QApplication.translate("SettingsMenu", "Enforce game\'s text rendering limitations", None, QtGui.QApplication.UnicodeUTF8))
        self.chkMangle.setChecked(True)
        self.chkMangle.setObjectName(_fromUtf8("chkMangle"))
        self.verticalLayout_9.addWidget(self.chkMangle)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem1)
        self.horizontalLayout_7.addLayout(self.verticalLayout_9)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.chkTagHighlight = QtGui.QCheckBox(self.groupBox_2)
        self.chkTagHighlight.setEnabled(False)
        self.chkTagHighlight.setText(QtGui.QApplication.translate("SettingsMenu", "Tag highlighting", None, QtGui.QApplication.UnicodeUTF8))
        self.chkTagHighlight.setObjectName(_fromUtf8("chkTagHighlight"))
        self.verticalLayout_8.addWidget(self.chkTagHighlight)
        self.chkTermHighlight = QtGui.QCheckBox(self.groupBox_2)
        self.chkTermHighlight.setText(QtGui.QApplication.translate("SettingsMenu", "Terminology highlighting", None, QtGui.QApplication.UnicodeUTF8))
        self.chkTermHighlight.setChecked(True)
        self.chkTermHighlight.setObjectName(_fromUtf8("chkTermHighlight"))
        self.verticalLayout_8.addWidget(self.chkTermHighlight)
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_5.setTitle(QtGui.QApplication.translate("SettingsMenu", "Languages", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_9.setContentsMargins(-1, 4, -1, 8)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_10 = QtGui.QLabel(self.groupBox_5)
        self.label_10.setText(QtGui.QApplication.translate("SettingsMenu", "Original", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_9.addWidget(self.label_10)
        self.txtLangOrig = QtGui.QLineEdit(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtLangOrig.sizePolicy().hasHeightForWidth())
        self.txtLangOrig.setSizePolicy(sizePolicy)
        self.txtLangOrig.setMaximumSize(QtCore.QSize(24, 16777215))
        self.txtLangOrig.setInputMask(QtGui.QApplication.translate("SettingsMenu", "<AA; ", None, QtGui.QApplication.UnicodeUTF8))
        self.txtLangOrig.setText(QtGui.QApplication.translate("SettingsMenu", "ja", None, QtGui.QApplication.UnicodeUTF8))
        self.txtLangOrig.setMaxLength(2)
        self.txtLangOrig.setObjectName(_fromUtf8("txtLangOrig"))
        self.horizontalLayout_9.addWidget(self.txtLangOrig)
        self.label_11 = QtGui.QLabel(self.groupBox_5)
        self.label_11.setText(QtGui.QApplication.translate("SettingsMenu", "Translated", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_9.addWidget(self.label_11)
        self.txtLangTrans = QtGui.QLineEdit(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtLangTrans.sizePolicy().hasHeightForWidth())
        self.txtLangTrans.setSizePolicy(sizePolicy)
        self.txtLangTrans.setMaximumSize(QtCore.QSize(24, 16777215))
        self.txtLangTrans.setInputMask(QtGui.QApplication.translate("SettingsMenu", "<AA; ", None, QtGui.QApplication.UnicodeUTF8))
        self.txtLangTrans.setText(QtGui.QApplication.translate("SettingsMenu", "en", None, QtGui.QApplication.UnicodeUTF8))
        self.txtLangTrans.setObjectName(_fromUtf8("txtLangTrans"))
        self.horizontalLayout_9.addWidget(self.txtLangTrans)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.verticalLayout_8.addWidget(self.groupBox_5)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem3)
        self.horizontalLayout_7.addLayout(self.verticalLayout_8)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_4 = QtGui.QGroupBox(self.tabPrefs)
        self.groupBox_4.setTitle(QtGui.QApplication.translate("SettingsMenu", "Building", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_6.setContentsMargins(-1, 4, -1, 8)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.chkPackData00 = QtGui.QCheckBox(self.groupBox_4)
        self.chkPackData00.setEnabled(True)
        self.chkPackData00.setText(QtGui.QApplication.translate("SettingsMenu", "Pack data00", None, QtGui.QApplication.UnicodeUTF8))
        self.chkPackData00.setChecked(False)
        self.chkPackData00.setObjectName(_fromUtf8("chkPackData00"))
        self.horizontalLayout_6.addWidget(self.chkPackData00)
        self.chkPackData01 = QtGui.QCheckBox(self.groupBox_4)
        self.chkPackData01.setText(QtGui.QApplication.translate("SettingsMenu", "Pack data01", None, QtGui.QApplication.UnicodeUTF8))
        self.chkPackData01.setChecked(True)
        self.chkPackData01.setObjectName(_fromUtf8("chkPackData01"))
        self.horizontalLayout_6.addWidget(self.chkPackData01)
        self.chkQuickBuild = QtGui.QCheckBox(self.groupBox_4)
        self.chkQuickBuild.setText(QtGui.QApplication.translate("SettingsMenu", "Quick build (no compression)", None, QtGui.QApplication.UnicodeUTF8))
        self.chkQuickBuild.setObjectName(_fromUtf8("chkQuickBuild"))
        self.horizontalLayout_6.addWidget(self.chkQuickBuild)
        self.chkBuildISO = QtGui.QCheckBox(self.groupBox_4)
        self.chkBuildISO.setText(QtGui.QApplication.translate("SettingsMenu", "Build ISO", None, QtGui.QApplication.UnicodeUTF8))
        self.chkBuildISO.setChecked(True)
        self.chkBuildISO.setObjectName(_fromUtf8("chkBuildISO"))
        self.horizontalLayout_6.addWidget(self.chkBuildISO)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        self.groupBox_3 = QtGui.QGroupBox(self.tabPrefs)
        self.groupBox_3.setTitle(QtGui.QApplication.translate("SettingsMenu", "Misc", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_7.setContentsMargins(-1, 4, -1, 8)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.chkExpandTrees = QtGui.QCheckBox(self.groupBox_3)
        self.chkExpandTrees.setText(QtGui.QApplication.translate("SettingsMenu", "Automatically expand similarity trees", None, QtGui.QApplication.UnicodeUTF8))
        self.chkExpandTrees.setChecked(True)
        self.chkExpandTrees.setObjectName(_fromUtf8("chkExpandTrees"))
        self.verticalLayout_7.addWidget(self.chkExpandTrees)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.tabWidget.addTab(self.tabPrefs, _fromUtf8(""))
        self.tabLocs = QtGui.QWidget()
        self.tabLocs.setObjectName(_fromUtf8("tabLocs"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.tabLocs)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.scrFileLocs = QtGui.QScrollArea(self.tabLocs)
        self.scrFileLocs.setAutoFillBackground(False)
        self.scrFileLocs.setStyleSheet(_fromUtf8(""))
        self.scrFileLocs.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrFileLocs.setFrameShadow(QtGui.QFrame.Plain)
        self.scrFileLocs.setLineWidth(0)
        self.scrFileLocs.setWidgetResizable(True)
        self.scrFileLocs.setObjectName(_fromUtf8("scrFileLocs"))
        self.scrFileLocsContents = QtGui.QWidget()
        self.scrFileLocsContents.setGeometry(QtCore.QRect(0, 0, 403, 366))
        self.scrFileLocsContents.setAutoFillBackground(True)
        self.scrFileLocsContents.setStyleSheet(_fromUtf8(""))
        self.scrFileLocsContents.setObjectName(_fromUtf8("scrFileLocsContents"))
        self.gridLayout_2 = QtGui.QGridLayout(self.scrFileLocsContents)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_2 = QtGui.QLabel(self.scrFileLocsContents)
        self.label_2.setText(QtGui.QApplication.translate("SettingsMenu", "ISO file", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.txtIsoFile = QtGui.QLineEdit(self.scrFileLocsContents)
        self.txtIsoFile.setObjectName(_fromUtf8("txtIsoFile"))
        self.gridLayout_2.addWidget(self.txtIsoFile, 1, 1, 1, 1)
        self.btnIsoFile = QtGui.QPushButton(self.scrFileLocsContents)
        self.btnIsoFile.setText(QtGui.QApplication.translate("SettingsMenu", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.btnIsoFile.setObjectName(_fromUtf8("btnIsoFile"))
        self.gridLayout_2.addWidget(self.btnIsoFile, 1, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.scrFileLocsContents)
        self.label_3.setText(QtGui.QApplication.translate("SettingsMenu", "data00 directory", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.txtData00Dir = QtGui.QLineEdit(self.scrFileLocsContents)
        self.txtData00Dir.setObjectName(_fromUtf8("txtData00Dir"))
        self.gridLayout_2.addWidget(self.txtData00Dir, 2, 1, 1, 1)
        self.btnData00Dir = QtGui.QPushButton(self.scrFileLocsContents)
        self.btnData00Dir.setText(QtGui.QApplication.translate("SettingsMenu", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.btnData00Dir.setObjectName(_fromUtf8("btnData00Dir"))
        self.gridLayout_2.addWidget(self.btnData00Dir, 2, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.scrFileLocsContents)
        self.label_4.setText(QtGui.QApplication.translate("SettingsMenu", "data01 directory", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.txtData01Dir = QtGui.QLineEdit(self.scrFileLocsContents)
        self.txtData01Dir.setObjectName(_fromUtf8("txtData01Dir"))
        self.gridLayout_2.addWidget(self.txtData01Dir, 3, 1, 1, 1)
        self.btnData01Dir = QtGui.QPushButton(self.scrFileLocsContents)
        self.btnData01Dir.setText(QtGui.QApplication.translate("SettingsMenu", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.btnData01Dir.setObjectName(_fromUtf8("btnData01Dir"))
        self.gridLayout_2.addWidget(self.btnData01Dir, 3, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.scrFileLocsContents)
        self.label_6.setText(QtGui.QApplication.translate("SettingsMenu", "Editor GFX directory", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 9, 0, 1, 1)
        self.txtGFXDir = QtGui.QLineEdit(self.scrFileLocsContents)
        self.txtGFXDir.setObjectName(_fromUtf8("txtGFXDir"))
        self.gridLayout_2.addWidget(self.txtGFXDir, 9, 1, 1, 1)
        self.btnGFXDir = QtGui.QPushButton(self.scrFileLocsContents)
        self.btnGFXDir.setText(QtGui.QApplication.translate("SettingsMenu", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.btnGFXDir.setObjectName(_fromUtf8("btnGFXDir"))
        self.gridLayout_2.addWidget(self.btnGFXDir, 9, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.scrFileLocsContents)
        self.label_7.setText(QtGui.QApplication.translate("SettingsMenu", "Voice directory", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 10, 0, 1, 1)
        self.txtVoice = QtGui.QLineEdit(self.scrFileLocsContents)
        self.txtVoice.setObjectName(_fromUtf8("txtVoice"))
        self.gridLayout_2.addWidget(self.txtVoice, 10, 1, 1, 1)
        self.btnVoice = QtGui.QPushButton(self.scrFileLocsContents)
        self.btnVoice.setText(QtGui.QApplication.translate("SettingsMenu", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.btnVoice.setObjectName(_fromUtf8("btnVoice"))
        self.gridLayout_2.addWidget(self.btnVoice, 10, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.scrFileLocsContents)
        self.label_5.setText(QtGui.QApplication.translate("SettingsMenu", "Terminology csv", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 11, 0, 1, 1)
        self.txtTerminology = QtGui.QLineEdit(self.scrFileLocsContents)
        self.txtTerminology.setObjectName(_fromUtf8("txtTerminology"))
        self.gridLayout_2.addWidget(self.txtTerminology, 11, 1, 1, 1)
        self.btnTerminology = QtGui.QPushButton(self.scrFileLocsContents)
        self.btnTerminology.setText(QtGui.QApplication.translate("SettingsMenu", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.btnTerminology.setObjectName(_fromUtf8("btnTerminology"))
        self.gridLayout_2.addWidget(self.btnTerminology, 11, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.scrFileLocsContents)
        self.label_8.setText(QtGui.QApplication.translate("SettingsMenu", "Copy changes to...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 14, 0, 1, 1)
        self.txtCopy = QtGui.QLineEdit(self.scrFileLocsContents)
        self.txtCopy.setObjectName(_fromUtf8("txtCopy"))
        self.gridLayout_2.addWidget(self.txtCopy, 14, 1, 1, 1)
        self.btnCopy = QtGui.QPushButton(self.scrFileLocsContents)
        self.btnCopy.setText(QtGui.QApplication.translate("SettingsMenu", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCopy.setObjectName(_fromUtf8("btnCopy"))
        self.gridLayout_2.addWidget(self.btnCopy, 14, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.scrFileLocsContents)
        self.label_9.setText(QtGui.QApplication.translate("SettingsMenu", "Make backup to...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 15, 0, 1, 1)
        self.txtBackup = QtGui.QLineEdit(self.scrFileLocsContents)
        self.txtBackup.setObjectName(_fromUtf8("txtBackup"))
        self.gridLayout_2.addWidget(self.txtBackup, 15, 1, 1, 1)
        self.btnBackup = QtGui.QPushButton(self.scrFileLocsContents)
        self.btnBackup.setText(QtGui.QApplication.translate("SettingsMenu", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBackup.setObjectName(_fromUtf8("btnBackup"))
        self.gridLayout_2.addWidget(self.btnBackup, 15, 2, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem7, 16, 1, 1, 1)
        self.btnIsoDir = QtGui.QPushButton(self.scrFileLocsContents)
        self.btnIsoDir.setText(QtGui.QApplication.translate("SettingsMenu", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.btnIsoDir.setObjectName(_fromUtf8("btnIsoDir"))
        self.gridLayout_2.addWidget(self.btnIsoDir, 0, 2, 1, 1)
        self.txtIsoDir = QtGui.QLineEdit(self.scrFileLocsContents)
        self.txtIsoDir.setObjectName(_fromUtf8("txtIsoDir"))
        self.gridLayout_2.addWidget(self.txtIsoDir, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.scrFileLocsContents)
        self.label.setText(QtGui.QApplication.translate("SettingsMenu", "ISO directory", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.scrFileLocsContents)
        self.label_13.setText(QtGui.QApplication.translate("SettingsMenu", "Dupes csv", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 12, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.scrFileLocsContents)
        self.label_15.setText(QtGui.QApplication.translate("SettingsMenu", "Similarity database", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 13, 0, 1, 1)
        self.txtDupes = QtGui.QLineEdit(self.scrFileLocsContents)
        self.txtDupes.setObjectName(_fromUtf8("txtDupes"))
        self.gridLayout_2.addWidget(self.txtDupes, 12, 1, 1, 1)
        self.btnDupes = QtGui.QPushButton(self.scrFileLocsContents)
        self.btnDupes.setText(QtGui.QApplication.translate("SettingsMenu", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDupes.setObjectName(_fromUtf8("btnDupes"))
        self.gridLayout_2.addWidget(self.btnDupes, 12, 2, 1, 1)
        self.txtSimilarity = QtGui.QLineEdit(self.scrFileLocsContents)
        self.txtSimilarity.setObjectName(_fromUtf8("txtSimilarity"))
        self.gridLayout_2.addWidget(self.txtSimilarity, 13, 1, 1, 1)
        self.btnSimilarity = QtGui.QPushButton(self.scrFileLocsContents)
        self.btnSimilarity.setText(QtGui.QApplication.translate("SettingsMenu", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSimilarity.setObjectName(_fromUtf8("btnSimilarity"))
        self.gridLayout_2.addWidget(self.btnSimilarity, 13, 2, 1, 1)
        self.label_14 = QtGui.QLabel(self.scrFileLocsContents)
        self.label_14.setText(QtGui.QApplication.translate("SettingsMenu", "Build cache directory", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 4, 0, 1, 1)
        self.txtBuildCache = QtGui.QLineEdit(self.scrFileLocsContents)
        self.txtBuildCache.setObjectName(_fromUtf8("txtBuildCache"))
        self.gridLayout_2.addWidget(self.txtBuildCache, 4, 1, 1, 1)
        self.btnBuildCache = QtGui.QPushButton(self.scrFileLocsContents)
        self.btnBuildCache.setText(QtGui.QApplication.translate("SettingsMenu", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBuildCache.setObjectName(_fromUtf8("btnBuildCache"))
        self.gridLayout_2.addWidget(self.btnBuildCache, 4, 2, 1, 1)
        self.scrFileLocs.setWidget(self.scrFileLocsContents)
        self.horizontalLayout_8.addWidget(self.scrFileLocs)
        self.tabWidget.addTab(self.tabLocs, _fromUtf8(""))
        self.tabRepl = QtGui.QWidget()
        self.tabRepl.setObjectName(_fromUtf8("tabRepl"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabRepl)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.treeTextRepl = QtGui.QTreeWidget(self.tabRepl)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeTextRepl.sizePolicy().hasHeightForWidth())
        self.treeTextRepl.setSizePolicy(sizePolicy)
        self.treeTextRepl.setAlternatingRowColors(True)
        self.treeTextRepl.setIndentation(0)
        self.treeTextRepl.setRootIsDecorated(False)
        self.treeTextRepl.setUniformRowHeights(True)
        self.treeTextRepl.setItemsExpandable(False)
        self.treeTextRepl.setAllColumnsShowFocus(True)
        self.treeTextRepl.setHeaderHidden(False)
        self.treeTextRepl.setExpandsOnDoubleClick(False)
        self.treeTextRepl.setColumnCount(2)
        self.treeTextRepl.setObjectName(_fromUtf8("treeTextRepl"))
        self.treeTextRepl.headerItem().setText(0, QtGui.QApplication.translate("SettingsMenu", "Text", None, QtGui.QApplication.UnicodeUTF8))
        self.treeTextRepl.headerItem().setText(1, QtGui.QApplication.translate("SettingsMenu", "Replace with", None, QtGui.QApplication.UnicodeUTF8))
        item_0 = QtGui.QTreeWidgetItem(self.treeTextRepl)
        self.treeTextRepl.topLevelItem(0).setText(0, QtGui.QApplication.translate("SettingsMenu", "—-", None, QtGui.QApplication.UnicodeUTF8))
        self.treeTextRepl.topLevelItem(0).setText(1, QtGui.QApplication.translate("SettingsMenu", "–", None, QtGui.QApplication.UnicodeUTF8))
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_0 = QtGui.QTreeWidgetItem(self.treeTextRepl)
        self.treeTextRepl.topLevelItem(1).setText(0, QtGui.QApplication.translate("SettingsMenu", "--", None, QtGui.QApplication.UnicodeUTF8))
        self.treeTextRepl.topLevelItem(1).setText(1, QtGui.QApplication.translate("SettingsMenu", "—", None, QtGui.QApplication.UnicodeUTF8))
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.treeTextRepl.header().setCascadingSectionResizes(True)
        self.treeTextRepl.header().setDefaultSectionSize(200)
        self.treeTextRepl.header().setHighlightSections(False)
        self.treeTextRepl.header().setSortIndicatorShown(False)
        self.treeTextRepl.header().setStretchLastSection(True)
        self.verticalLayout_4.addWidget(self.treeTextRepl)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.btnNewRepl = QtGui.QPushButton(self.tabRepl)
        self.btnNewRepl.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNewRepl.setIcon(icon1)
        self.btnNewRepl.setObjectName(_fromUtf8("btnNewRepl"))
        self.horizontalLayout_5.addWidget(self.btnNewRepl)
        self.btnDelRepl = QtGui.QPushButton(self.tabRepl)
        self.btnDelRepl.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDelRepl.setIcon(icon2)
        self.btnDelRepl.setObjectName(_fromUtf8("btnDelRepl"))
        self.horizontalLayout_5.addWidget(self.btnDelRepl)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.tabWidget.addTab(self.tabRepl, _fromUtf8(""))
        self.tabTags = QtGui.QWidget()
        self.tabTags.setObjectName(_fromUtf8("tabTags"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tabTags)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.treeTags = QtGui.QTreeWidget(self.tabTags)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeTags.sizePolicy().hasHeightForWidth())
        self.treeTags.setSizePolicy(sizePolicy)
        self.treeTags.setAlternatingRowColors(True)
        self.treeTags.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.treeTags.setIndentation(0)
        self.treeTags.setRootIsDecorated(False)
        self.treeTags.setUniformRowHeights(True)
        self.treeTags.setItemsExpandable(False)
        self.treeTags.setAllColumnsShowFocus(True)
        self.treeTags.setHeaderHidden(False)
        self.treeTags.setExpandsOnDoubleClick(False)
        self.treeTags.setColumnCount(2)
        self.treeTags.setObjectName(_fromUtf8("treeTags"))
        self.treeTags.headerItem().setText(0, QtGui.QApplication.translate("SettingsMenu", "Tag", None, QtGui.QApplication.UnicodeUTF8))
        self.treeTags.headerItem().setText(1, QtGui.QApplication.translate("SettingsMenu", "Highlight", None, QtGui.QApplication.UnicodeUTF8))
        item_0 = QtGui.QTreeWidgetItem(self.treeTags)
        self.treeTags.topLevelItem(0).setText(0, QtGui.QApplication.translate("SettingsMenu", "lol", None, QtGui.QApplication.UnicodeUTF8))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_0.setBackground(0, brush)
        self.treeTags.topLevelItem(0).setText(1, QtGui.QApplication.translate("SettingsMenu", "#C86260", None, QtGui.QApplication.UnicodeUTF8))
        brush = QtGui.QBrush(QtGui.QColor(200, 98, 96))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item_0.setBackground(1, brush)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_0 = QtGui.QTreeWidgetItem(self.treeTags)
        self.treeTags.topLevelItem(1).setText(0, QtGui.QApplication.translate("SettingsMenu", "iffy", None, QtGui.QApplication.UnicodeUTF8))
        self.treeTags.topLevelItem(1).setText(1, QtGui.QApplication.translate("SettingsMenu", "#99D9EA", None, QtGui.QApplication.UnicodeUTF8))
        brush = QtGui.QBrush(QtGui.QColor(153, 217, 234))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item_0.setBackground(1, brush)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.treeTags.header().setCascadingSectionResizes(True)
        self.treeTags.header().setDefaultSectionSize(200)
        self.treeTags.header().setHighlightSections(False)
        self.treeTags.header().setSortIndicatorShown(False)
        self.treeTags.header().setStretchLastSection(True)
        self.verticalLayout_5.addWidget(self.treeTags)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.btnNewTag = QtGui.QPushButton(self.tabTags)
        self.btnNewTag.setText(_fromUtf8(""))
        self.btnNewTag.setIcon(icon1)
        self.btnNewTag.setObjectName(_fromUtf8("btnNewTag"))
        self.horizontalLayout_4.addWidget(self.btnNewTag)
        self.btnDelTag = QtGui.QPushButton(self.tabTags)
        self.btnDelTag.setText(_fromUtf8(""))
        self.btnDelTag.setIcon(icon2)
        self.btnDelTag.setObjectName(_fromUtf8("btnDelTag"))
        self.horizontalLayout_4.addWidget(self.btnDelTag)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.btnTagToTop = QtGui.QPushButton(self.tabTags)
        self.btnTagToTop.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/resultset_first.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnTagToTop.setIcon(icon3)
        self.btnTagToTop.setObjectName(_fromUtf8("btnTagToTop"))
        self.horizontalLayout_4.addWidget(self.btnTagToTop)
        self.btnTagUp = QtGui.QPushButton(self.tabTags)
        self.btnTagUp.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/resultset_previous.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnTagUp.setIcon(icon4)
        self.btnTagUp.setObjectName(_fromUtf8("btnTagUp"))
        self.horizontalLayout_4.addWidget(self.btnTagUp)
        self.btnTagDown = QtGui.QPushButton(self.tabTags)
        self.btnTagDown.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/resultset_next.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnTagDown.setIcon(icon5)
        self.btnTagDown.setObjectName(_fromUtf8("btnTagDown"))
        self.horizontalLayout_4.addWidget(self.btnTagDown)
        self.btnTagToBottom = QtGui.QPushButton(self.tabTags)
        self.btnTagToBottom.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/resultset_last.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnTagToBottom.setIcon(icon6)
        self.btnTagToBottom.setObjectName(_fromUtf8("btnTagToBottom"))
        self.horizontalLayout_4.addWidget(self.btnTagToBottom)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.tabTags, _fromUtf8(""))
        self.tabHacks = QtGui.QWidget()
        self.tabHacks.setObjectName(_fromUtf8("tabHacks"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabHacks)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lstHacks = QtGui.QListWidget(self.tabHacks)
        self.lstHacks.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lstHacks.setEditTriggers(QtGui.QAbstractItemView.EditKeyPressed)
        self.lstHacks.setViewMode(QtGui.QListView.ListMode)
        self.lstHacks.setObjectName(_fromUtf8("lstHacks"))
        item = QtGui.QListWidgetItem()
        item.setText(QtGui.QApplication.translate("SettingsMenu", "Swap O/X Buttons", None, QtGui.QApplication.UnicodeUTF8))
        item.setCheckState(QtCore.Qt.Checked)
        self.lstHacks.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setText(QtGui.QApplication.translate("SettingsMenu", "Map Name Centering", None, QtGui.QApplication.UnicodeUTF8))
        item.setCheckState(QtCore.Qt.Checked)
        self.lstHacks.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setText(QtGui.QApplication.translate("SettingsMenu", "Ammo/Present Menu (Names)", None, QtGui.QApplication.UnicodeUTF8))
        item.setCheckState(QtCore.Qt.Checked)
        self.lstHacks.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setText(QtGui.QApplication.translate("SettingsMenu", "Ammo/Present Menu (Line Length)", None, QtGui.QApplication.UnicodeUTF8))
        item.setCheckState(QtCore.Qt.Checked)
        self.lstHacks.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setText(QtGui.QApplication.translate("SettingsMenu", "Ammo/Present Menu (Previews)", None, QtGui.QApplication.UnicodeUTF8))
        item.setCheckState(QtCore.Qt.Checked)
        self.lstHacks.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setText(QtGui.QApplication.translate("SettingsMenu", "Long Ammo File Fix", None, QtGui.QApplication.UnicodeUTF8))
        item.setCheckState(QtCore.Qt.Checked)
        self.lstHacks.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setText(QtGui.QApplication.translate("SettingsMenu", "Fix Glyph Height", None, QtGui.QApplication.UnicodeUTF8))
        item.setCheckState(QtCore.Qt.Unchecked)
        self.lstHacks.addItem(item)
        self.verticalLayout_2.addWidget(self.lstHacks)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_12 = QtGui.QLabel(self.tabHacks)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setStyleSheet(_fromUtf8("margin-bottom: 1px;"))
        self.label_12.setText(QtGui.QApplication.translate("SettingsMenu", "System Menu Language", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_2.addWidget(self.label_12)
        self.cboHackLang = QtGui.QComboBox(self.tabHacks)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.cboHackLang.setFont(font)
        self.cboHackLang.setObjectName(_fromUtf8("cboHackLang"))
        self.cboHackLang.addItem(_fromUtf8(""))
        self.cboHackLang.setItemText(0, QtGui.QApplication.translate("SettingsMenu", "日本語", None, QtGui.QApplication.UnicodeUTF8))
        self.cboHackLang.addItem(_fromUtf8(""))
        self.cboHackLang.setItemText(1, QtGui.QApplication.translate("SettingsMenu", "English", None, QtGui.QApplication.UnicodeUTF8))
        self.cboHackLang.addItem(_fromUtf8(""))
        self.cboHackLang.setItemText(2, QtGui.QApplication.translate("SettingsMenu", "Français", None, QtGui.QApplication.UnicodeUTF8))
        self.cboHackLang.addItem(_fromUtf8(""))
        self.cboHackLang.setItemText(3, QtGui.QApplication.translate("SettingsMenu", "Español", None, QtGui.QApplication.UnicodeUTF8))
        self.cboHackLang.addItem(_fromUtf8(""))
        self.cboHackLang.setItemText(4, QtGui.QApplication.translate("SettingsMenu", "Deutsch", None, QtGui.QApplication.UnicodeUTF8))
        self.cboHackLang.addItem(_fromUtf8(""))
        self.cboHackLang.setItemText(5, QtGui.QApplication.translate("SettingsMenu", "Italiano", None, QtGui.QApplication.UnicodeUTF8))
        self.cboHackLang.addItem(_fromUtf8(""))
        self.cboHackLang.setItemText(6, QtGui.QApplication.translate("SettingsMenu", "Nederlands", None, QtGui.QApplication.UnicodeUTF8))
        self.cboHackLang.addItem(_fromUtf8(""))
        self.cboHackLang.setItemText(7, QtGui.QApplication.translate("SettingsMenu", "Português", None, QtGui.QApplication.UnicodeUTF8))
        self.cboHackLang.addItem(_fromUtf8(""))
        self.cboHackLang.setItemText(8, QtGui.QApplication.translate("SettingsMenu", "Русский", None, QtGui.QApplication.UnicodeUTF8))
        self.cboHackLang.addItem(_fromUtf8(""))
        self.cboHackLang.setItemText(9, QtGui.QApplication.translate("SettingsMenu", "한국어", None, QtGui.QApplication.UnicodeUTF8))
        self.cboHackLang.addItem(_fromUtf8(""))
        self.cboHackLang.setItemText(10, QtGui.QApplication.translate("SettingsMenu", "繁體中文", None, QtGui.QApplication.UnicodeUTF8))
        self.cboHackLang.addItem(_fromUtf8(""))
        self.cboHackLang.setItemText(11, QtGui.QApplication.translate("SettingsMenu", "简体中文", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout_2.addWidget(self.cboHackLang)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.btnReloadHacks = QtGui.QPushButton(self.tabHacks)
        self.btnReloadHacks.setText(QtGui.QApplication.translate("SettingsMenu", "Reload", None, QtGui.QApplication.UnicodeUTF8))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/arrow_refresh.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnReloadHacks.setIcon(icon7)
        self.btnReloadHacks.setObjectName(_fromUtf8("btnReloadHacks"))
        self.horizontalLayout_2.addWidget(self.btnReloadHacks)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.tabHacks, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(SettingsMenu)
        self.buttonBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(SettingsMenu)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), SettingsMenu.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), SettingsMenu.reject)
        QtCore.QObject.connect(self.chkSpellCheck, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cboSpellCheckLang.setEnabled)
        QtCore.QObject.connect(self.btnNewRepl, QtCore.SIGNAL(_fromUtf8("clicked()")), SettingsMenu.add_repl)
        QtCore.QObject.connect(self.btnDelRepl, QtCore.SIGNAL(_fromUtf8("clicked()")), SettingsMenu.del_repl)
        QtCore.QObject.connect(self.btnNewTag, QtCore.SIGNAL(_fromUtf8("clicked()")), SettingsMenu.add_tag)
        QtCore.QObject.connect(self.btnDelTag, QtCore.SIGNAL(_fromUtf8("clicked()")), SettingsMenu.del_tag)
        QtCore.QObject.connect(self.btnTagToTop, QtCore.SIGNAL(_fromUtf8("clicked()")), SettingsMenu.move_tag_top)
        QtCore.QObject.connect(self.btnTagUp, QtCore.SIGNAL(_fromUtf8("clicked()")), SettingsMenu.move_tag_up)
        QtCore.QObject.connect(self.btnTagDown, QtCore.SIGNAL(_fromUtf8("clicked()")), SettingsMenu.move_tag_down)
        QtCore.QObject.connect(self.btnTagToBottom, QtCore.SIGNAL(_fromUtf8("clicked()")), SettingsMenu.move_tag_bottom)
        QtCore.QMetaObject.connectSlotsByName(SettingsMenu)
        SettingsMenu.setTabOrder(self.tabWidget, self.chkPlayVoices)
        SettingsMenu.setTabOrder(self.chkPlayVoices, self.chkPlayBGM)
        SettingsMenu.setTabOrder(self.chkPlayBGM, self.chkSpellCheck)
        SettingsMenu.setTabOrder(self.chkSpellCheck, self.cboSpellCheckLang)
        SettingsMenu.setTabOrder(self.cboSpellCheckLang, self.chkTextRepl)
        SettingsMenu.setTabOrder(self.chkTextRepl, self.chkSmartQuotes)
        SettingsMenu.setTabOrder(self.chkSmartQuotes, self.chkTagHighlight)
        SettingsMenu.setTabOrder(self.chkTagHighlight, self.chkTermHighlight)
        SettingsMenu.setTabOrder(self.chkTermHighlight, self.chkPackData00)
        SettingsMenu.setTabOrder(self.chkPackData00, self.chkPackData01)
        SettingsMenu.setTabOrder(self.chkPackData01, self.chkBuildISO)
        SettingsMenu.setTabOrder(self.chkBuildISO, self.chkExpandTrees)
        SettingsMenu.setTabOrder(self.chkExpandTrees, self.txtIsoFile)
        SettingsMenu.setTabOrder(self.txtIsoFile, self.btnIsoFile)
        SettingsMenu.setTabOrder(self.btnIsoFile, self.txtData00Dir)
        SettingsMenu.setTabOrder(self.txtData00Dir, self.btnData00Dir)
        SettingsMenu.setTabOrder(self.btnData00Dir, self.txtData01Dir)
        SettingsMenu.setTabOrder(self.txtData01Dir, self.btnData01Dir)
        SettingsMenu.setTabOrder(self.btnData01Dir, self.txtGFXDir)
        SettingsMenu.setTabOrder(self.txtGFXDir, self.btnGFXDir)
        SettingsMenu.setTabOrder(self.btnGFXDir, self.txtVoice)
        SettingsMenu.setTabOrder(self.txtVoice, self.btnVoice)
        SettingsMenu.setTabOrder(self.btnVoice, self.txtTerminology)
        SettingsMenu.setTabOrder(self.txtTerminology, self.btnTerminology)
        SettingsMenu.setTabOrder(self.btnTerminology, self.txtCopy)
        SettingsMenu.setTabOrder(self.txtCopy, self.btnCopy)
        SettingsMenu.setTabOrder(self.btnCopy, self.txtBackup)
        SettingsMenu.setTabOrder(self.txtBackup, self.btnBackup)
        SettingsMenu.setTabOrder(self.btnBackup, self.treeTags)
        SettingsMenu.setTabOrder(self.treeTags, self.btnNewTag)
        SettingsMenu.setTabOrder(self.btnNewTag, self.btnDelTag)
        SettingsMenu.setTabOrder(self.btnDelTag, self.btnTagToTop)
        SettingsMenu.setTabOrder(self.btnTagToTop, self.btnTagUp)
        SettingsMenu.setTabOrder(self.btnTagUp, self.btnTagDown)
        SettingsMenu.setTabOrder(self.btnTagDown, self.btnTagToBottom)
        SettingsMenu.setTabOrder(self.btnTagToBottom, self.treeTextRepl)
        SettingsMenu.setTabOrder(self.treeTextRepl, self.btnNewRepl)
        SettingsMenu.setTabOrder(self.btnNewRepl, self.btnDelRepl)
        SettingsMenu.setTabOrder(self.btnDelRepl, self.lstHacks)
        SettingsMenu.setTabOrder(self.lstHacks, self.cboHackLang)
        SettingsMenu.setTabOrder(self.cboHackLang, self.btnReloadHacks)
        SettingsMenu.setTabOrder(self.btnReloadHacks, self.buttonBox)

    def retranslateUi(self, SettingsMenu):
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPrefs), QtGui.QApplication.translate("SettingsMenu", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLocs), QtGui.QApplication.translate("SettingsMenu", "File Locations", None, QtGui.QApplication.UnicodeUTF8))
        self.treeTextRepl.setSortingEnabled(False)
        __sortingEnabled = self.treeTextRepl.isSortingEnabled()
        self.treeTextRepl.setSortingEnabled(False)
        self.treeTextRepl.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRepl), QtGui.QApplication.translate("SettingsMenu", "Text Replacement", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.treeTags.isSortingEnabled()
        self.treeTags.setSortingEnabled(False)
        self.treeTags.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTags), QtGui.QApplication.translate("SettingsMenu", "Tags", None, QtGui.QApplication.UnicodeUTF8))
        self.lstHacks.setSortingEnabled(False)
        __sortingEnabled = self.lstHacks.isSortingEnabled()
        self.lstHacks.setSortingEnabled(False)
        item = self.lstHacks.item(0)
        item = self.lstHacks.item(1)
        item = self.lstHacks.item(2)
        item = self.lstHacks.item(3)
        item = self.lstHacks.item(4)
        item = self.lstHacks.item(5)
        item = self.lstHacks.item(6)
        self.lstHacks.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabHacks), QtGui.QApplication.translate("SettingsMenu", "Hacks", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
